### ISSUE TITLE
 如果列表 view 设置 delegate，会出错

### ISSUE THREAD

**Issue by blloc** [sensorsdata/sa-sdk-ios#10]
神策在 hook tableView，或者 collectionView 的时候，如果列表的代理是设置给 view 的，是无法识别的,你们只是做了控制器的

**Comment by wangzhzh** [comment]
你是指无法识别还是指程序本身 crash 了？

**Comment by blloc** [comment]
无法识别~

**Comment by blloc** [comment]
因为你的代码只针对控制器做了 hook

**Comment by wangzhzh** [comment]
是的，这个我们后续会优化一下，OK了我再单独通知你

**Comment by blloc** [comment]
嗯呢，还有一个是针对 tableView sectionHeader 或者 sectionFooter ，这些生成路径是不准确的，没有做特殊处理

**Comment by huangqiaobo** [comment]
+1，delegate不一定设置给当前的VC

**Comment by yaoyue** [comment]
感谢反馈，1.10.15 版本开始，tableView 和 collectionView 点击事件的采集已经重新实现，可以支持非 VC 实现 delegate 的点击事件的采集。
