### ISSUE TITLE
Crash:-[SensorsAnalyticsSDK trackEventObject:properties:]

### ISSUE THREAD

**Issue by FatTiger1** [sensorsdata/sa-sdk-ios#101]
![截屏2022-08-05 15 35 51](https://user-images.githubusercontent.com/41276124/183026570-35f35409-65f0-4c7d-bf11-a9b98c8baca7.png)

**Comment by minchaozhang** [comment]
辛苦提供一下 SDK 版本，设备及详细的堆栈信息
