### ISSUE TITLE
Deeplink 代码与文件名大小写不一致

### ISSUE THREAD

**Issue by wenbingzuo** [sensorsdata/sa-sdk-ios#102]
大小写不一致会抛出警告：non-portable path to file '"SensorsAnalyticsSDK+Deeplink.h"'; specified path differs in case from file name on disk.

```objective-c
#import "SensorsAnalyticsSDK+DeepLink.h"
#import "SADeepLinkManager.h"
```

如果 `GCC_TREAT_WARNINGS_AS_ERRORS = YES` 的话，会编译出错。

**Comment by jjksam** [comment]
已创建了[Pull Request](https://github.com/sensorsdata/sa-sdk-ios/pull/107)，可以看看。
