### ISSUE TITLE
期望支持 XCode 自带的 Swift Package Manager 来集成神策

### ISSUE THREAD

**Issue by lishanhu** [sensorsdata/sa-sdk-ios#105]
期望支持 XCode 自带的 Swift Package Manager 来集成神策，目前主流的开源组件都支持了。

**Comment by minchaozhang** [comment]
可以使用 https://github.com/sensorsdata/sa-sdk-ios-spm

**Comment by lishanhu** [comment]
确实这个方案可行支持SwiftPM，不过提供的路径是本地路径，用户一开始是没有那个XCFramework的，将会报错。
