### ISSUE TITLE
SensorsAnalyticsSDK 4.4.6 打包报错

### ISSUE THREAD

**Issue by JanzTam** [sensorsdata/sa-sdk-ios#109]
Xcode 13.2.1 
sensors_analytics_flutter_plugin 插件 V2.2.0 版本，此版本依赖SDK 4.4.6版本
打包构建会报错，希望尽快解决。

目前临时解决方法：
sensors_analytics_flutter_plugin 使用 V2.1.1版本，改此插件源代码，将 sdk 版本写死 V4.4.4

**Comment by yaoyue** [comment]
您好，目前 iOS SDK v4.4.6 已发布，所以理论上是可以引用到，您这边的报错详情可以贴一下嘛？

**Comment by JanzTam** [comment]
用的 xcodebuild 命令打包，之前一直好好的，更了最新的版本就报错了。

```
While building module 'sensors_analytics_flutter_plugin' imported from /Users/xxx/.jenkins/workspace/flutter-project/ios/Runner/GeneratedPluginRegistrant.m:94:
    In file included from <module-includes>:1:
    In file included from /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/sensors_analytics_flutter_plugin/sensors_analytics_flutter_plugin.framework/Headers/sensors_analytics_flutter_plugin-umbrella.h:13:
    /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/sensors_analytics_flutter_plugin/sensors_analytics_flutter_plugin.framework/Headers/SAFlutterGlobalPropertyPlugin.h:22:9: error: include of non-modular header inside framework module 'sensors_analytics_flutter_plugin.SAFlutterGlobalPropertyPlugin': '/Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/SensorsAnalyticsSDK/SensorsAnalyticsSDK.framework/Headers/SAPropertyPlugin.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import "SAPropertyPlugin.h"
            ^
    1 error generated.
    /Users/xxx/.jenkins/workspace/flutter-project/ios/Runner/GeneratedPluginRegistrant.m:94:9: fatal error: could not build module 'sensors_analytics_flutter_plugin'
    #import <sensors_analytics_flutter_plugin/SensorsAnalyticsFlutterPlugin.h>
     ~~~~~~~^
    5 warnings and 2 errors generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Encountered error while archiving for device.
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by yaoyue** [comment]
创建的 Swift 项目打包报错问题，Flutter 插件刚刚发布  v2.2.1 修复该问题，您这边可以更新试试哈

**Comment by yaoyue** [comment]
> 用的 xcodebuild 命令打包，之前一直好好的，更了最新的版本就报错了。
> 
> ```
> While building module 'sensors_analytics_flutter_plugin' imported from /Users/xxx/.jenkins/workspace/flutter-project/ios/Runner/GeneratedPluginRegistrant.m:94:
>     In file included from <module-includes>:1:
>     In file included from /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/sensors_analytics_flutter_plugin/sensors_analytics_flutter_plugin.framework/Headers/sensors_analytics_flutter_plugin-umbrella.h:13:
>     /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/sensors_analytics_flutter_plugin/sensors_analytics_flutter_plugin.framework/Headers/SAFlutterGlobalPropertyPlugin.h:22:9: error: include of non-modular header inside framework module 'sensors_analytics_flutter_plugin.SAFlutterGlobalPropertyPlugin': '/Users/xxx/Library/Developer/Xcode/DerivedData/Runner-ggnubhlsllktunggdvrbhvpilhei/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/SensorsAnalyticsSDK/SensorsAnalyticsSDK.framework/Headers/SAPropertyPlugin.h' [-Werror,-Wnon-modular-include-in-framework-module]
>     #import "SAPropertyPlugin.h"
>             ^
>     1 error generated.
>     /Users/xxx/.jenkins/workspace/flutter-project/ios/Runner/GeneratedPluginRegistrant.m:94:9: fatal error: could not build module 'sensors_analytics_flutter_plugin'
>     #import <sensors_analytics_flutter_plugin/SensorsAnalyticsFlutterPlugin.h>
>      ~~~~~~~^
>     5 warnings and 2 errors generated.
>     note: Using new build system
>     note: Planning
>     note: Build preparation complete
>     note: Building targets in dependency order
> 
> Encountered error while archiving for device.
> Build step 'Execute shell' marked build as failure
> Archiving artifacts
> Finished: FAILURE
> ```

创建的 Swift 项目打包报错问题，Flutter 插件刚刚发布 v2.2.1 修复该问题，您这边可以更新试试

**Comment by JanzTam** [comment]
> 

v2.2.1 打包正常了
