### ISSUE TITLE
源码方式集成报错

### ISSUE THREAD

**Issue by Lee0820** [sensorsdata/sa-sdk-ios#113]
源码继承为什么这个文件的这里会报错呢，工程是ARC工程，而且我注释了这个就好了，别的文件里的这个也没报错

![A9FDBBBD-7A72-4D7C-A673-5F3BE99A83D4](https://user-images.githubusercontent.com/11679563/206491272-74a7fbc3-6383-46b0-bb58-b3032d952e0a.png)

**Comment by yaoyue** [comment]
这个判断确实多余了，我们尽快修改。但是您这边的报错，看看是否开启了 「Treat Warnings as Errors」配置，如果是的话，可以关闭再试试

**Comment by yaoyue** [comment]
[release v4.5.9](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v4.5.9) 修复了这个问题，您可以更新代码再试试：
https://github.com/sensorsdata/sa-sdk-ios/commit/48fefdc59421ea209c2783ab7d2c0ca6843216be
