### ISSUE TITLE
Crash -[UIApplication(mob) _mob_sendAction:to:from:forEvent:] NSInvalidArgumentException - -[<NSTextContentStorage: <address>> locationFromLocation:withOffset:] received invalid location (null)

### ISSUE THREAD

**Issue by CarusCha** [sensorsdata/sa-sdk-ios#114]
'SensorsAnalyticsSDK', '4.2.4'
![218075259-a33ba6dd-56b1-47c5-a5e6-348d2909a403](https://user-images.githubusercontent.com/86467735/220547742-98909be3-e8c7-421a-99fa-9cf89ccc144f.png)
![Screenshot 2023-02-10 at 6 55 58 PM](https://user-images.githubusercontent.com/86467735/218075273-64fd2056-f82e-40e9-8f9a-8df5fd153bcf.png)

**Comment by yaoyue** [comment]
您好，看起来是 NSTextStorage 处理出现问题，只是我们 hook 了 -[UIApplication sendAction:to:from:forEvent:]。所以调用堆栈里面有我们接口，但是最终崩溃原因，应该和神策 SDK 没关系。您可以再检查业务代码看看
