### ISSUE TITLE
flushBulkSize判断逻辑错误

### ISSUE THREAD

**Issue by ishall1** [sensorsdata/sa-sdk-ios#115]
![image](https://user-images.githubusercontent.com/8748505/220312637-bfe9b1eb-429f-41cc-8645-6f86a8062197.png)

如图所示，这里的这个判断逻辑**<=**，应该是**<**才是设计的逻辑吧，不然总会多1才能触发上报

**Comment by yaoyue** [comment]
感谢反馈，这块确实不太严谨，我们尽快修复~

**Comment by yaoyue** [comment]
您好，我们 4.5.11 修改了代码注释说明，确保和实现逻辑一致，您可以再看看
