### ISSUE TITLE
[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] NSInvalidArgumentException - *** -[NSTaggedPointerString stringByReplacingCharactersInRange:withString:]: nil argument

### ISSUE THREAD

**Issue by AisinLiu** [sensorsdata/sa-sdk-ios#116]
iOS SDK Version 4.4.1

-[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:]
NSInvalidArgumentException - *** -[NSTaggedPointerString stringByReplacingCharactersInRange:withString:]: nil argument

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x12a654 __exceptionPreprocess
1  libobjc.A.dylib                0x5bcc objc_exception_throw
2  Foundation                     0x62098 +[NSUserDefaults(NSUserDefaults_NSURLExtras) _web_defaultsDidChange]
3  TextInput                      0x145f4 -[TIDocumentState(StateTransitions) documentStateAfterReplacingText:withText:]
4  UIKitCore                      0x856220 -[UIKeyboardImpl setDocumentStateForAutocorrection:]
5  UIKitCore                      0x856828 __82-[UIKeyboardImpl acceptAutocorrection:executionContextPassingTIKeyboardCandidate:]_block_invoke_2
6  UIKitCore                      0x856680 -[UIKeyboardImpl acceptAutocorrection:executionContextPassingTIKeyboardCandidate:]
7  UIKitCore                      0x855b08 -[UIKeyboardImpl acceptAutocorrectionForWordTerminator:executionContextPassingTIKeyboardCandidate:]
8  UIKitCore                      0x8559d8 __56-[UIKeyboardImpl acceptAutocorrectionForWordTerminator:]_block_invoke
9  UIKitCore                      0x87c4fc -[UIKeyboardTaskEntry execute:]
10 UIKitCore                      0x87af30 -[UIKeyboardTaskQueue continueExecutionOnMainThread]
11 UIKitCore                      0x87b284 -[UIKeyboardTaskQueue performTaskOnMainThread:waitUntilDone:]
12 UIKitCore                      0x8558f4 -[UIKeyboardImpl acceptAutocorrectionForWordTerminator:]
13 UIKitCore                      0x858a04 -[UIKeyboardImpl acceptAutocorrection]
14 UIKitCore                      0x858bd0 __38-[UIKeyboardImpl acceptAutocorrection]_block_invoke
15 UIKitCore                      0x87c4fc -[UIKeyboardTaskEntry execute:]
16 UIKitCore                      0x87af30 -[UIKeyboardTaskQueue continueExecutionOnMainThread]
17 UIKitCore                      0x858b7c -[UIKeyboardImpl acceptAutocorrection]
18 UIKitCore                      0x83e720 -[UIKeyboardImpl setDelegate:force:]
19 UIKitCore                      0x52a178 -[UIInputResponderController _reloadInputViewsForKeyWindowSceneResponder:]
20 UIKitCore                      0x5299a4 -[UIInputResponderController _reloadInputViewsForResponder:]
21 UIKitCore                      0xa60a60 -[UIResponder(UIResponderInputViewAdditions) reloadInputViews]
22 WebKit                         0x59cbf4 -[WKContentView(WKInteraction) _hideKeyboard]
23 WebKit                         0x342c -[WKContentViewAccessibility _hideKeyboard]
24 WebKit                         0x59d6a8 -[WKContentView(WKInteraction) _elementDidBlur]
25 WebKit                         0x590cb8 -[WKContentView(WKInteraction) endEditingAndUpdateFocusAppearanceWithReason:]
26 WebKit                         0x59a5f8 -[WKContentView(WKInteraction) accessoryDone]
27 UIKitCore                      0x591430 -[UIWebFormAccessory done:]
28 UIKitCore                      0xa2f72c -[UIApplication sendAction:to:from:forEvent:]
29 MTAppProduction                0x449c54 -[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] + 62 (UIApplication+SAAutoTrack.m:62)
30 UIKitCore                      0xda478 __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke
31 UIKitCore                      0xda308 -[_UIButtonBarTargetAction _invoke:forEvent:]
32 UIKitCore                      0xa2f72c -[UIApplication sendAction:to:from:forEvent:]
33 MTAppProduction                0x449c54 -[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] + 62 (UIApplication+SAAutoTrack.m:62)
34 UIKitCore                      0x43fed4 -[UIControl sendAction:to:forEvent:]
35 UIKitCore                      0x44022c -[UIControl _sendActionsForEvents:withEvent:]
36 UIKitCore                      0x43f250 -[UIControl touchesEnded:withEvent:]
37 UIKitCore                      0xa6949c -[UIWindow _sendTouchesForEvent:]
38 UIKitCore                      0xa6ac64 -[UIWindow sendEvent:]
39 UIKitCore                      0xa468ec -[UIApplication sendEvent:]
40 UIKit                          0x1f80c -[UIApplicationAccessibility sendEvent:]
41 MTAppProduction                0x3bbf9c -[MTApplication sendEvent:] + 30 (MTApplication.m:30)
42 UIKitCore                      0xac7970 __dispatchPreprocessedEventFromEventQueue
43 UIKitCore                      0xaca4ec __handleEventQueueInternal
44 UIKitCore                      0xac2168 __handleHIDEventFetcherDrain
45 CoreFoundation                 0xa8ad8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
46 CoreFoundation                 0xa8a30 __CFRunLoopDoSource0
47 CoreFoundation                 0xa81b8 __CFRunLoopDoSources0
48 CoreFoundation                 0xa31e8 __CFRunLoopRun
49 CoreFoundation                 0xa2ba8 CFRunLoopRunSpecific
50 GraphicsServices               0x3344 GSEventRunModal
51 UIKitCore                      0xa2e3e4 UIApplicationMain
52 MTAppProduction                0x4bd3e0 main + 14 (main.m:14)
53 libdyld.dylib                  0x18f0 start

**Comment by xsgoing** [comment]
mark

**Comment by yaoyue** [comment]
您好，看起来是系统问题，只是我们 hook 了  -[UIApplication sendAction:to:from:forEvent:]。所以调用堆栈里面有我们接口，但是最终崩溃原因，应该和神策 SDK 没关系。网上其他开发者也有相同问题及方案，您可以参考看看：
https://developer.apple.com/forums/thread/674886

https://stackoverflow.com/questions/58687888/nstaggedpointerstring-stringbyreplacingcharactersinrangewithstring-nil-argum

![image](https://github.com/sensorsdata/sa-sdk-ios/assets/10718825/07271bd0-ba8e-4bff-b88a-93aac1ca7f35)
