### ISSUE TITLE
bugly崩溃错误

### ISSUE THREAD

**Issue by luin4** [sensorsdata/sa-sdk-ios#117]
您好，有谁遇到bugly崩溃报错在这里的么？SASignalHandler
![1679283707255](https://user-images.githubusercontent.com/13867369/226241483-2ea3a850-b063-4e78-923b-97e57e41e7e0.jpg)

**Comment by luin4** [comment]
补充一下，iOS16系统以上会出现，但复现不出

**Comment by yaoyue** [comment]
SASignalHandler 是用于崩溃采集，可能是我们 SASignalHandler 捕获了这次 crash，但是 crash 来源不确认来自哪里。您是哪个客户呢？方便在客户对接群提供详细 crash 堆栈、线程和数量信息嘛

**Comment by luin4** [comment]
好的，我找下对接群，届时和您们沟通下
