### ISSUE TITLE
iOS双卡设备使用流量时，获取网络类型可能不准确

### ISSUE THREAD

**Issue by LeonYin945** [sensorsdata/sa-sdk-ios#121]
比如当前使用的副卡流量（4G），实际获取的主卡的网络类型（3G）
![image](https://github.com/sensorsdata/sa-sdk-ios/assets/13748427/6c0b4154-d1ac-473c-9111-98e5d38e8001)

**Comment by LeonYin945** [comment]
主要问题在于获取网络类型的方式，通过serviceCurrentRadioAccessTechnology获取到的是所有卡的网络类型，这里直接获取了allValues.lastObject，个人理解这里没法保证，一定取到当前使用的卡的网络类型。
是否可以通过状态栏去获取下当前的网络状态？

**Comment by yaoyue** [comment]
通过状态栏获取风险太高了，随时可能会被 Apple 换掉，并且面临私有 API 的审核问题
