### ISSUE TITLE
Bugly上报了一个崩溃，提示与Sensor有关，求助！

### ISSUE THREAD

**Issue by DoneLiu** [sensorsdata/sa-sdk-ios#122]
崩溃如图：
![image](https://github.com/sensorsdata/sa-sdk-ios/assets/15603425/e0220679-85ca-4e3c-94dd-e883ee363f33)

**Comment by yaoyue** [comment]
看崩溃堆栈，只是 UIControl 触发事件后，最终崩溃在键盘和输入框相关，只是神策 SDK 采集全埋点，hook 了 响应率调用的 senAction:  方法，所以堆栈中，有一行这句代码，但是崩溃堆栈和 SDK 没有关系。
