### ISSUE TITLE
iOS16+崩溃

### ISSUE THREAD

**Issue by Louis-Zeng** [sensorsdata/sa-sdk-ios#123]
![Pasted Graphic](https://github.com/sensorsdata/sa-sdk-ios/assets/7512465/32977c65-51f0-4da5-97ef-b2158813fa99)
最新版本4.5.20在iOS16崩溃，iOS15不会

**Comment by LuckinDog** [comment]
这个看了下，应该是 collection 在实现的时候一个 self-sizing cells 的问题，可以参考这篇文档看下：https://stackoverflow.com/questions/70213395/self-sizing-collection-view-enters-a-recursive-loop-in-ios-15 ， 或者提供个 demo 这边复现下
