### ISSUE TITLE
Xcode15+iOS17 设置wkwebView的user-agent失效

### ISSUE THREAD

**Issue by gratefulHeart** [sensorsdata/sa-sdk-ios#129]
+ (void)saveUserAgent:(NSString *)userAgent {
    if (![SAValidator isValidString:userAgent]) {
        return;
    }
    
    NSDictionary *dictionnary = [[NSDictionary alloc] initWithObjectsAndKeys:userAgent, @"UserAgent", nil];
    [[NSUserDefaults standardUserDefaults] registerDefaults:dictionnary];
    [[NSUserDefaults standardUserDefaults] synchronize];
}

这段代码在Xcode15+iOS17 设置wkwebView的user-agent失效

**Comment by yaoyue** [comment]
请使用新版打通方案吧 enableJavaScriptBridge
