### ISSUE TITLE
carthage 编译失败

### ISSUE THREAD

**Issue by hyjfine** [sensorsdata/sa-sdk-ios#13]
*** Checking out sa-sdk-ios at "v1.9.2"
*** xcodebuild output can be found in /var/folders/7z/gkbw5rv50fj5w6d6hx15nh2c0000gn/T/carthage-xcodebuild.AxHda9.log
*** Skipped building sa-sdk-ios due to the error:
Dependency "sa-sdk-ios" has no shared framework schemes

mac下carthage编译失败

**Comment by Zuoweixiang** [comment]
@hyjfine  我们后期会添加 carthage 的支持

**Comment by wangzhzh** [comment]
v1.11.1 已至此  carthage，请参考：https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v1.11.1
