### ISSUE TITLE
4.7.0版本打包报错

### ISSUE THREAD

**Issue by debugcheck** [sensorsdata/sa-sdk-ios#130]
Showing All Errors Only
/XXXXX/Pods/Pods.xcodeproj: Signing for "SensorsAnalyticsSDK-SensorsAnalyticsSDK" requires a development team. Select a development team in the Signing & Capabilities editor.

<img width="795" alt="image" src="https://github.com/sensorsdata/sa-sdk-ios/assets/4171147/2bde7c9b-d084-4237-b441-feb05c56a9dd">

**Comment by yaoyue** [comment]
SDK 代码开源，自己打包签名即可 ~
