### ISSUE TITLE
Collecitonview ： collectionView: willDisplayCell:forItemAtIndexPath: 问题 如果是NSProxy 没有办法转发出去

### ISSUE THREAD

**Issue by LeonLeeboy** [sensorsdata/sa-sdk-ios#133]
SAExposureDelegateProxy 类里面
- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath {
 。。。 
    //invoke original
    SEL methodSelector = @selector(collectionView:willDisplayCell:forItemAtIndexPath:);
    if (class_getInstanceMethod(collectionView.delegate.class, methodSelector)) {
        [SAExposureDelegateProxy invokeWithTarget:self selector:methodSelector, collectionView, cell, indexPath];
    } else if ([collectionView.delegate.class isKindOfClass:[NSProxy class]]) {
        /**修改代码 begin*/
        [SAExposureDelegateProxy invokeWithTarget:self selector:methodSelector, collectionView, cell, indexPath];
        /**修改代码 end*/
       
    }

    [collectionView.sensorsdata_exposure_delegateHashTable removeAllObjects];
}

**Comment by yaoyue** [comment]
RxSwift 类似的场景（使用 NSProxy 之类的），目前曝光暂不支持
