### ISSUE TITLE
添加隐私清单；

### ISSUE THREAD

**Issue by JC-Passerby** [sensorsdata/sa-sdk-ios#134]
<img width="838" alt="image" src="https://github.com/sensorsdata/sa-sdk-ios/assets/13104486/f21778f3-e3f4-48d3-aade-63b89833913d">
本SDK使用了该API，审核需要添加相应的隐私清单，请大佬尽快更新；

**Comment by yaoyue** [comment]
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/13104486/325691461-f21778f3-e3f4-48d3-aade-63b89833913d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTc2OTAsIm5iZiI6MTcxNDA5NzM5MCwicGF0aCI6Ii8xMzEwNDQ4Ni8zMjU2OTE0NjEtZjIxNzc4ZjMtZTNmNC00OGQzLWFhZGUtNjNiODk4MzM5MTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAyMDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMzRiYjZiY2RmMzBmODM3MzEwNDdkM2Q0YzY4N2Y1N2NiNzVmZDEwMTA1MTY4N2E1MGVkODBlNmVhNTkyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8dAmvhpEfQrQGj6WW292Fr2jBlbnlbxHD-nfOJiYgM"> 本SDK使用了该API，审核需要添加相应的隐私清单，请大佬尽快更新；

你可以直接更新 SDK或看看 SDK 的 PrivacyInfo.xcprivacy 文件

**Comment by JC-Passerby** [comment]
你们只有这两个 还少着呐




刘某某。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sensorsdata/sa-sdk-ios"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月26日(星期五) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sensorsdata/sa-sdk-ios] 添加隐私清单； (Issue #134)





 
Closed #134 as completed.

**Comment by yaoyue** [comment]
> 你们只有这两个 还少着呐 刘某某。 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sensorsdata/sa-sdk-ios" ***@***.***&gt;; 发送时间:&nbsp;2024年4月26日(星期五) 上午10:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sensorsdata/sa-sdk-ios] 添加隐私清单； (Issue #134) Closed #134 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![image](https://github.com/sensorsdata/sa-sdk-ios/assets/10718825/6f27d822-3ef9-418e-97e4-b09b55300a22)
