### ISSUE TITLE
只针对iOS 18beta版本，神策NSObject (DelegateProxy)里面的hook方法崩溃

### ISSUE THREAD

**Issue by DoneLiu** [sensorsdata/sa-sdk-ios#137]
![image](https://github.com/user-attachments/assets/f2698e7d-af63-4b0c-aa4f-dba710f9d7c3)
神策NSObject (DelegateProxy)里面的hook方法崩溃，只针对iOS 18beta版本，
iOS 上线很久的老版本，也开始出现崩溃，都是iOS18的beta版本，怀疑是神策sdk的hook方法没有针对iOS18做兼容吗？帮忙帮忙看看，目前我们使用的神策SDK版本是，2.5.5版本
![image](https://github.com/user-attachments/assets/ef26e19c-395d-4aae-af6c-53025c0e122d)
是否升级SDK到最新的4.7.0版本能解决崩溃问题？（iOS18beta版本之前没有过此类问题，感觉2.5.5版本应该也没有问题）

**Comment by yaoyue** [comment]
iOS18 beta4 版本新出的系统 bug，beta3 无此问题，在 navigationController 调用 setViewControllers 时候，会系统内部调用了 respondsToSelector: 并传了一个野指针，然后我们开启曝光后，会 hook respondsToSelector: 并做了  NSStringFromSelector 操作，从而出现崩溃。
我们目前正在修复，近期会发布。

您这边可以关闭曝光，暂时避免这种问题。并且只是 beta4 新出的系统 bug，后期 Apple 应该也会修复 ~

**Comment by DoneLiu** [comment]
> iOS18 beta4 版本新出的系统 bug，beta3 无此问题，在 navigationController 调用 setViewControllers 时候，会系统内部调用了 respondsToSelector: 并传了一个野指针，然后我们开启曝光后，会 hook respondsToSelector: 并做了 NSStringFromSelector 操作，从而出现崩溃。 我们目前正在修复，近期会发布。
> 
> 您这边可以关闭曝光，暂时避免这种问题。并且只是 beta4 新出的系统 bug，后期 Apple 应该也会修复 ~

神策新版本SDK的推出时间预计在什么时候呢？

**Comment by yaoyue** [comment]
您这边是哪个客户？我们发布后，让售后同学通知一下 ~

**Comment by DoneLiu** [comment]
> @DoneLiu 您这边是哪个客户？我们发布后，让售后同学通知一下 ~

胖达信息

**Comment by yaoyue** [comment]
@DoneLiu  v4.7.1 已修复问题：[v4.7.1](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v4.7.1)

**Comment by yaoyue** [comment]
@DoneLiu v4.7.1 已修复问题：[v4.7.1](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v4.7.1)

**Comment by DoneLiu** [comment]
> @DoneLiu v4.7.1 已修复问题：[v4.7.1](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v4.7.1)

OK，感谢
