### ISSUE TITLE
sa-sdk-ios-4.7.0 crash

### ISSUE THREAD

**Issue by xsgoing** [sensorsdata/sa-sdk-ios#138]
Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x3b44 _platform_strlen + 4
1  Foundation                     0x14500 NSStringFromSelector + 56
2  MTAPProduction                 0x2f10ec -[NSObject(DelegateProxy) sensorsdata_respondsToSelector:] + 56 (NSObject+SADelegateProxy.m:56)

**Comment by yaoyue** [comment]
您这边是哪个客户，请联系售后技术顾问提供协助 ~

**Comment by yaoyue** [comment]
iOS18 beta 版本的 bug，导致某些场景 SDK 崩溃，升级到最新版 SDK，即  v4.7.2 即可解决此问题
