### ISSUE TITLE
ApplicationWillTerminate 回调时不能正常记录打点信息

### ISSUE THREAD

**Issue by wrlqwe** [sensorsdata/sa-sdk-ios#14]
监听系统 UIApplicationWillTerminateNotification 通知，自测时直接杀进程，执行了 SD 的 track 方法，打点记录不上，跟踪发现 SD 未写库，设备iPhone7p iOS 11.2.5，目测其他版本也有此问题。

**Comment by Zuoweixiang** [comment]
@wrlqwe  谢谢 我们会尽快验证该问题

**Comment by Zuoweixiang** [comment]
@wrlqwe 最近两天我们会release 版本用来解决该问题，及时更新SDK即可

**Comment by wrlqwe** [comment]
@Zuoweixiang 给力

**Comment by Zuoweixiang** [comment]
@wrlqwe 你们使用最新的 SDK 应该解决了该问题吧？
