### ISSUE TITLE
代码与文件名大小写不一致

### ISSUE THREAD

**Issue by wenbingzuo** [sensorsdata/sa-sdk-ios#140]
4.8.1 版本有以下警告，该警告会导致依赖方也有警告

Non-portable path to file '"SensorsAnalyticsSDK+Deeplink.h"'; specified path differs in case from file name on disk

```objective-c
#if __has_include("SensorsAnalyticsSDK+DeepLink.h")
#import "SensorsAnalyticsSDK+DeepLink.h"
#import "SAAdvertisingConfig.h"
#endif
```

Non-portable path to file '"UIVIew+SensorsAnalytics.h"'; specified path differs in case from file name on disk

```objective-c
#if __has_include("UIView+SensorsAnalytics.h")
#import "UIView+SensorsAnalytics.h"
#endif
```

**Comment by yaoyue** [comment]
确认v4.8.1 未发现类似问题

**Comment by wenbingzuo** [comment]
来 @yaoyue 

引用的地方：https://github.com/sensorsdata/sa-sdk-ios/blob/v4.8.1/SensorsAnalyticsSDK/Core/SensorsAnalyticsSDK.h#L39
文件：https://github.com/sensorsdata/sa-sdk-ios/blob/v4.8.1/SensorsAnalyticsSDK/Deeplink/SensorsAnalyticsSDK%2BDeeplink.h

**Comment by yaoyue** [comment]
哪个大小写不同？

**Comment by wenbingzuo** [comment]
@yaoyue 两处

- 代码：`#import "SensorsAnalyticsSDK+DeepLink.h"`
- 文件：`SensorsAnalyticsSDK/Deeplink/SensorsAnalyticsSDK+Deeplink.h`
- 不同：Deep**L**ink.h - Deep**l**ink.h

- 代码：`#import "UIView+SensorsAnalytics.h"`
- 文件：`SensorsAnalyticsSDK/UIRelated/UIVIew+SensorsAnalytics.h`
- 不同：UIV**i**ew - UIV**I**ew

**Comment by yaoyue** [comment]
你集成的可能是老版的，检查 v4.8.1 未发现类似问题

**Comment by wenbingzuo** [comment]
这都是 4.8.1 版本的代码，你可以看下

引用的地方：https://github.com/sensorsdata/sa-sdk-ios/blob/v4.8.1/SensorsAnalyticsSDK/Core/SensorsAnalyticsSDK.h#L39
文件：https://github.com/sensorsdata/sa-sdk-ios/blob/v4.8.1/SensorsAnalyticsSDK/Deeplink/SensorsAnalyticsSDK%2BDeeplink.h

**Comment by yaoyue** [comment]
好的，感谢~
发现 github 本地和远程代码不同，之前提交代码，github 似乎没有完全替换掉
