### ISSUE TITLE
4.3.6 ios 崩溃

### ISSUE THREAD

**Issue by ifgyong** [sensorsdata/sa-sdk-ios#141]
![image](https://github.com/user-attachments/assets/d78a248f-483f-458f-a5f5-4c9e2ea8cab0)
![image](https://github.com/user-attachments/assets/d45b7a55-cc24-486f-b1e9-bd245fdf39de)

用户大部分崩溃的18.1

**Comment by yaoyue** [comment]
iOS18 beta 版本的 bug，导致某些场景 SDK 崩溃，升级到最新版 SDK，即 v4.7.2 即可解决此问题
