### ISSUE TITLE
Xcode16.0编译报错

### ISSUE THREAD

**Issue by wendeqiang** [sensorsdata/sa-sdk-ios#143]
使用最新版本4.8.2之后依然编译报错，报错内容如下：
![截屏2024-10-12 11 44 58](https://github.com/user-attachments/assets/dac847d9-6792-4e34-87d2-f926c306b3d2)
![截屏2024-10-12 11 45 12](https://github.com/user-attachments/assets/eb95abe0-d4f3-4a08-994a-1957458e525f)

**Comment by wendeqiang** [comment]
xcode15.4运行正常，pod 'SensorsAnalyticsSDK',   '4.8.2'     版本在xcode16.0上编译报错

**Comment by yaoyue** [comment]
这明显显示  HybridSDK 报错。。。。。。。

**Comment by wendeqiang** [comment]
这不也是神策SDK的一部分吗

**Comment by wendeqiang** [comment]
不好意思，看错了
