### ISSUE TITLE
 iOS Native SDK Crash

### ISSUE THREAD

**Issue by xsgoing** [sensorsdata/sa-sdk-ios#144]
SDK Version: 4.7.2
iOS System Version：iOS16-18
Crash file & line：0x686cd0 -[NSObject(SAKeyValueObserver) sensorsdata_dealloc] + 179 (NSObject+SAKeyValueObserver.m:179)

**Comment by yaoyue** [comment]
哪家客户，请提供详细的堆栈信息 ~
