### ISSUE TITLE
路径获取的缺陷

### ISSUE THREAD

**Issue by blloc** [sensorsdata/sa-sdk-ios#16]
当三个按钮在 storybord 生成的，之后三个分别链接一个方法，那么他们的路径完全一致,如图：这样区分不出来的哦

**Comment by blloc** [comment]
![image](https://user-images.githubusercontent.com/8268339/38860291-746e8b62-4262-11e8-8161-719b8fcb5ff0.png)

**Comment by Zuoweixiang** [comment]
@blloc  感谢反馈，我们现在的处理方案确实会有这样的问题，正在寻找好的解决方式

**Comment by blloc** [comment]
加上该控件在父控件中的位置的索引 不就解决了吗

**Comment by Zuoweixiang** [comment]
@blloc 

> 还有一个问题，目前你的 cell 获取到的只有 row，没有 section 的，这个也不太准确的，建议把 section 加上。

 目前我们还在开发中，这个问题应该会很快解决了，TableView， collectionView 路径采集会有所进步。

**Comment by yaoyue** [comment]
> 还有一个问题，目前你的 cell 获取到的只有 row，没有 section 的，这个也不太准确的，建议把 section 加上。

这个在 v1.11.1 版本得到修复，欢迎体验

**Comment by minchaozhang** [comment]
可以使用 UIView 的扩展属性 sensorsAnalyticsViewID，给控件添加一个唯一标识符，解决相同控件的问题
