### ISSUE TITLE
1.1.17Tag UIImageView 的 addGestureRecognizer 被替换掉

### ISSUE THREAD

**Issue by KenwayCen** [sensorsdata/sa-sdk-ios#24]
如果将 神策的初始化放到 + load() 方法 中，则UIImageView 添加的手势会被替换掉不执行。

**Comment by Zuoweixiang** [comment]
@KenwayCen 辛苦提供下详细的使用案例，谢谢

**Comment by yaoyue** [comment]
我们验证没有这种问题，您这边用的是 v1.1.17 么？建议用最新版的再试试？
