### ISSUE TITLE
出现数据当天全部不上报情况，过一天可能又恢复上报了  TAT！查了各种可能，有朋友遇到过嘛？sdk版本1.10.20

### ISSUE THREAD

**Issue by alex0811** [sensorsdata/sa-sdk-ios#28]

**Comment by yaoyue** [comment]
您好，出现问题的手机，是 12.0-12.0.1 的系统并且没有连接 WiFi 么?

**Comment by yaoyue** [comment]
我们测试发现存在少数 12.0 和 12.0.1 的机型存在系统 API 错误， serviceCurrentRadioAccessTechnology 返回空，导致判断网络不准确，从而没有发送数据。在 v1.11.1 版本已经修复，感谢反馈

**Comment by alex0811** [comment]
> 您好，出现问题的手机，是 12.0-12.0.1 的系统并且没有连接 WiFi 么?

感谢您的回

**Comment by alex0811** [comment]
> 我们测试发现存在少数 12.0 和 12.0.1 的机型存在系统 API 错误， serviceCurrentRadioAccessTechnology 返回空，导致判断网络不准确，从而没有发送数据。在 v1.11.1 版本已经修复，感谢反馈

感谢修复！
