### ISSUE TITLE
这种方式可能在某些情况下不安全, 在主线程但是非主队列中. 参考SDWebImage

### ISSUE THREAD

**Issue by Quanhua-Guan** [sensorsdata/sa-sdk-ios#30]
https://github.com/sensorsdata/sa-sdk-ios/blob/fbd1992d696d306a411efed321d8f65e88237b29/SensorsAnalyticsSDK/NSThread%2BSAHelpers.m#L18

参考SDWebImage实现 https://github.com/SDWebImage/SDWebImage/blob/3f29a3ef1e5b980f1f31949f22938525bd5dfe12/SDWebImage/SDWebImageCompat.h#L89

**Comment by yaoyue** [comment]
感谢反馈，我们尽快优化

**Comment by yaoyue** [comment]
v1.11.3 版已做相关优化，再次感谢反馈。

**Comment by yaoyue** [comment]
已经修复并更新，v1.11.5，欢迎体验。
