### ISSUE TITLE
crash when open AddressSanitizer

### ISSUE THREAD

**Issue by manajay** [sensorsdata/sa-sdk-ios#32]
![image](https://user-images.githubusercontent.com/13750333/57765165-80d72200-7737-11e9-8881-903025627298.png)

Signed integer overflow: 2112820162 * 31 cannot be represented in type 'int'

**Comment by yaoyue** [comment]
感谢您的反馈，我们尽快优化

**Comment by yaoyue** [comment]
您这边有具体的 crash 信息么？这边为了保证后端_ 和 SDK 的 hash 校验一致，需要用 Int。

**Comment by manajay** [comment]
![image](https://user-images.githubusercontent.com/13750333/59960593-e5d32400-94fc-11e9-887d-2e4b026f352b.png)
![image](https://user-images.githubusercontent.com/13750333/59960597-f4b9d680-94fc-11e9-9df0-3aab6463f977.png)
开启 AddressSanitizer 会崩溃
SDK 版本 : 1.11.1

**Comment by wangzhzh** [comment]
@yaoyue

**Comment by yaoyue** [comment]
@manajay 您这边有方式可以复现么？我们尝试开启 AddressSanitizer  没有类似问题。您这边 Xcode 和 设备 版本分别是多少呢？

**Comment by cntrump** [comment]
看这个算法，emoji或者汉字（长文章），很容易溢出

**Comment by wangzhzh** [comment]
hashCode 本身就可以是负数，为了保证与后端的 hashCode（Java）算法一致。

**Comment by cntrump** [comment]
> hashCode 本身就可以是负数，为了保证与后端的 hashCode（Java）算法一致。

我是指，从hash算法逻辑上看，hash会一直累加，如果计算的 NSString 内容很长，就有益处的可能。
图里的提示也显示上整形溢出。
