### ISSUE TITLE
为什么将 v1.11.1 从 Cocoapods 中移除？

### ISSUE THREAD

**Issue by ziiip** [sensorsdata/sa-sdk-ios#33]
正常不是保留旧的版本么？这样移除了，旧代码引用了这个版本就不能正常使用了。

**Comment by yaoyue** [comment]
不好意思，这个版本的 SDK 有点问题，新用户第一次启动的时候，公共属性覆盖不到 $AppStart 事件。我们怕影响到客户数据，所以进行了下线。您可以使用 pod 'SensorsAnalyticsSDK' 不指定版本再执行 pod update 进行更新。给您造成不便，再次抱歉。

**Comment by ziiip** [comment]
你们不应该移除旧版本，如果用户选择不升级，那个是用户自己的事情，用户自己承担后果就好了。如果觉得用户会使用旧版本出问题，那就邮件用户更新就好了呀？
Podfile 是要被列入 git 管理，你这样做，旧代码该怎么办？每次 checkout 代码都要手动改一下 Podfile 才能正常工作？引用了这个版本的现有分支都要改 Podfile 才能正常工作？每次这些分支合并的时候，都要处理同一个的冲突？

算我孤陋寡闻，这种公开 SDK 的管理方式还是第一次见或第一次碰到。

**Comment by wangzhzh** [comment]
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/4361619/61163878-a61fbb00-a543-11e9-930b-17bfd1d8f332.png">
