### ISSUE TITLE
iOS 13 崩溃问题：UIThreadSafeNode 找不到 nextResponder 方法

### ISSUE THREAD

**Issue by xezun** [sensorsdata/sa-sdk-ios#35]
我们的App收到有关 iOS13 测试版中神策埋点SDK的两个崩溃，请帮忙解决：

UncaughtException=>NSInvalidArgumentException', reason: '-[UIThreadSafeNode nextResponder]: unrecognized selector sent to instance ' =>BWA=>-[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] (UIApplication+AutoTrack.m:69)

UncaughtException=>NSInvalidArgumentException', reason: '-[UIThreadSafeNode nextResponder]: unrecognized selector sent to instance ' =>CoreFoundation=>

SDK 版本：1.10.20

**Comment by wangzhzh** [comment]
好的，我们尽快分析和修复

**Comment by LuckinDog** [comment]
This should be a bug for iOS 13 beta versions, and was fixed on iOS 13 release versions(like 13.2.2). please refer to  
https://stackoverflow.com/questions/33807812/uiwebview-uithreadsafenode-responderforediting-crash
