### ISSUE TITLE
采集多次激活事件

### ISSUE THREAD

**Issue by minchaozhang** [sensorsdata/sa-sdk-ios#38]
激活事件有不少首日为假的情况

**Comment by dev-dylan** [comment]
已发现问题原因，下版本会修复。方案如下：
1、 先读取 NSuserDefault 数据，已激活直接返回
2、未获取到数据再读取 keychain，keychain 读取成功后更新 NSuserDefault 状态
3、都未获取到时触发激活事件，再更新 keychain 和 NSUserDefault 状态

**Comment by minchaozhang** [comment]
修复版本：[Release 1.11.13](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v1.11.13)
