### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by yaoyue** [sensorsdata/sa-sdk-ios#41]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

最近使用 SDK 构建版本，收到 Apple 邮件，节选内容如上，请问这边后期有啥打算嘛？

**Comment by chatwyn** [comment]
同上

**Comment by minchaozhang** [comment]
新增预编译宏。
使用 pod 集成方式：
```pod 'SensorsAnalyticsSDK', :subspecs => ['DISABLE_UIWEBVIEW']```
如果使用源码集成，请添加 SENSORS_ANALYTICS_DISABLE_UIWEBVIEW=1 预编译宏
![image](https://user-images.githubusercontent.com/38648223/65757456-bfe79c00-e149-11e9-9e4a-0bb5cd4a511e.png)


修复版本：[Release 1.11.13](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v1.11.13)
