### ISSUE TITLE
iOS 13.1.2 Crash

### ISSUE THREAD

**Issue by lipeiaiwo** [sensorsdata/sa-sdk-ios#44]
iOS13.1.2 crash
下面是日志

-[SAJSONUtil JSONSerializeObject:] (in latin) (SAJSONUtil.m:59)
-[MessageQueueBySqlite addObejct:withType:] (in latin) (MessageQueueBySqlite.m:0)
-[SensorsAnalyticsSDK enqueueWithType:andEvent:] (in latin) (SensorsAnalyticsSDK.m:1477)
__53-[SensorsAnalyticsSDK track:withProperties:withType:]_block_invoke (in latin) (SensorsAnalyticsSDK.m:1740)

**Comment by minchaozhang** [comment]
#42

**Comment by minchaozhang** [comment]
新版本已修复，感谢反馈
