### ISSUE TITLE
'SensorsAnalyticsSDK.h' file not found

### ISSUE THREAD

**Issue by iShawnWang** [sensorsdata/sa-sdk-ios#45]
## 环境
Xcode : Version 11.0 (11A420a)
iOS 13.1.2 iPhone Xr 真机

## 报错

![FBC9F514-6312-4B7D-BBE2-F58F68CA706C](https://user-images.githubusercontent.com/20266594/67648552-f8f57500-f970-11e9-855d-8e10ffd1cbec.jpg)

## Podfile

```
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '9.0'
use_frameworks!

target 'ace' do
  ... 

  pod 'Sentry'
  pod 'SensorsAnalyticsSDK', :subspecs => ['ENABLE_REACT_NATIVE_APPCLICK', 'LOG']
  pod 'RNSensorsAnalyticsModule', :path => '../node_modules/@sensors.data/react-native-sensors-analytics'

  ...

end

**Comment by dev-dylan** [comment]
https://github.com/sensorsdata/react-native-sensors-analytics/releases/tag/v1.1.2
新版本 RN 已更新，您可以更新版本后按照官方文档重新集成。

**Comment by iShawnWang** [comment]
已经发布了 Cocoapods 吗 ?
