### ISSUE TITLE
IGListKit 中的collectionViewCell点击事件无法被正确track

### ISSUE THREAD

**Issue by yudun1989** [sensorsdata/sa-sdk-ios#46]
看了一下源码，原因是因为：

- `sa-sdk`通过`setDelegate`来对delegate对象的`collectionview:didSelectItemAtIndexPath:`进行swizzle
- 进行swizzle的时候会一层一层的遍历父对象，通过`class_getInstanceMethod`来拿到originalSelector
- `IGListKit`中的`IGListAdapterProxy`并没有实现相关方法，而是通过`forwardingTargetForSelector`将selector的代理到其他的对象中。

这样确实比较棘手，因为貌似直接拿不到原始的`selector`。有没有可能这样：

如果遍历不到originalSelector，尝试查看这个对象是不是响应`collectionview:didSelectItemAtIndexPath:`，如果遍历没找到实现，但是又做出了相应，则说明这个是一个proxy，通过`forwardingTargetForSelector`来继续进行查找，找到实现了这个方法的对象，进行swizzle。

`UITableView` 同理

**Comment by minchaozhang** [comment]
对于这样的第三方的控件，可以考虑使用代码埋点

**Comment by yudun1989** [comment]
> 对于这样的第三方的控件，可以考虑使用代码埋点

想问下为什么不考虑通过 `forwardingTargetForSelector` 来继续查找？性能考虑？

**Comment by minchaozhang** [comment]
我现在也在维护着这个 SDK。就像你说的每个人写代码的方式都不会一样，所以让 SDK 支持所有的第三方库那也是不现实的。所以我们基本建议对于这样的第三方库都使用代码埋点。

> 想问下为什么不考虑通过 forwardingTargetForSelector 来继续查找？性能考虑？
使用 forwardingTargetForSelector 的方式我们也都调研过，这个方式是可以解决一些问题，但是同时也会有一些新的问题（例如：多个使用这种方式拦截的库可能回造成冲突）。
如果你觉得有更好的方式来实现 UITableView 或者 UICollectionView 的全埋点，可以给我提一个 PR，帮助我们一起改进 SDK。

**Comment by minchaozhang** [comment]
我现在也在维护着这个 SDK。
就像你说的每个人写代码的方式都不太一样，让 SDK 去实现采集所有不同实现方式的点击事件也是不太现实的。因此对于这样非苹果官方建议的实现方式，我们一般都建议使用代码埋点。

> 想问下为什么不考虑通过 forwardingTargetForSelector 来继续查找？性能考虑？

现在 SDK 使用的方式确实是不完美的，对于使用 forwardingTargetForSelector 的方式，是能解决一些问题，但是也同样有一些缺陷（例如：多个使用这种方式进行拦截的库可能会造成冲突）。
如果您觉得有更好的采集 UITableView 或者 UICollectionView 点击事件的方式，可以给我们提 PR，帮助我们共同改进 SDK。

**Comment by yudun1989** [comment]
> 我现在也在维护着这个 SDK。
> 就像你说的每个人写代码的方式都不太一样，让 SDK 去实现采集所有不同实现方式的点击事件也是不太现实的。因此对于这样非苹果官方建议的实现方式，我们一般都建议使用代码埋点。
> 
> > 想问下为什么不考虑通过 forwardingTargetForSelector 来继续查找？性能考虑？
> 
> 现在 SDK 使用的方式确实是不完美的，对于使用 forwardingTargetForSelector 的方式，是能解决一些问题，但是也同样有一些缺陷（例如：多个使用这种方式进行拦截的库可能会造成冲突）。
> 如果您觉得有更好的采集 UITableView 或者 UICollectionView 点击事件的方式，可以给我们提 PR，帮助我们共同改进 SDK。

想具体问下『缺陷』的细节问题：多个使用这种方式进行拦截的库为什么会造成冲突？使用`forwardingTargetForSelector`只是为了找到实现selector的target，对其进行swizzle。为什么会造成冲突呢。

**Comment by minchaozhang** [comment]
您可以了解下这个库：[Aspects](https://github.com/steipete/Aspects)，使用的是消息转发的方式实现 Method Swizzle。在实际使用过程中，就和我们的正常的 Swizzle 方式有些冲突，可能造成循环调用。

> 另，IGList写的方式符合苹果的规范，他调用了setDelegate方法把一个对象设置成了delegate，并且这个delegate符合UICollectionViewDelegate的protocol。

我对这个库并不了解😂，不过按你所说的 `IGListAdapterProxy` 并没有实现  `collectionview:didSelectItemAtIndexPath:`，所以是不是其实并不是完全按苹果的实现方式去做的呢？

**Comment by yudun1989** [comment]
> 您可以了解下这个库：[Aspects](https://github.com/steipete/Aspects)，使用的是消息转发的方式实现 Method Swizzle。在实际使用过程中，就和我们的正常的 Swizzle 方式有些冲突，可能造成循环调用。
> 
> > 另，IGList写的方式符合苹果的规范，他调用了setDelegate方法把一个对象设置成了delegate，并且这个delegate符合UICollectionViewDelegate的protocol。
> 
> 我对这个库并不了解😂，不过按你所说的 `IGListAdapterProxy` 并没有实现 `collectionview:didSelectItemAtIndexPath:`，所以是不是其实并不是完全按苹果的实现方式去做的呢？


苹果并没有要求具体用户要怎么做呀，苹果只要求设置一个代理并且实现相关的代理方法。具体怎么实现苹果不关心啊。
我的意思是作为一个SDK，不应该预设用户以某种方式进行实现，毕竟苹果并没有要求实现的时候不能使用proxy来做？

```
The delegate must adopt the UICollectionViewDelegate protocol. The collection view maintains a weak reference to the delegate object.

The delegate object is responsible for managing selection behavior and interactions with individual items.
```
`adopt` 就可以了啊。具体怎么`adopt`，是用户的事情呀。

**Comment by minchaozhang** [comment]
是的，您说的挺对的，感谢您的意见。之前的方案确实不能做到满足所有的实现方式，我们现在也在尝试其他更好的解决方案。
如果可以希望您能帮我们一起改进 SDK。

**Comment by lijiaxin2333** [comment]
现在这个问题在新版本上已经修复了吗, 我使用的是4.3.0版本还存在类似的问题
