### ISSUE TITLE
iOS 10.2&10.2.1上面奔溃 

### ISSUE THREAD

**Issue by tavia250** [sensorsdata/sa-sdk-ios#47]
0 libsystem_kernel.dylib | __pthread_kill + 8
-- | --
1 libsystem_pthread.dylib | pthread_kill + 112
2 libsystem_c.dylib | abort + 140
3 libsystem_malloc.dylib | __nano_vet_and_size_of_live
4 libsystem_malloc.dylib | _nano_realloc + 648
5 libsystem_malloc.dylib | malloc_zone_realloc + 180
6 CoreFoundation | ___CFStringCreateImmutableFunnel3 + 692
7 CoreFoundation | CFStringCreateFromExternalRepresentation + 104
8 Foundation | -[NSPlaceholderString initWithData:encoding:] + 148
9 SensorsAnalyticsSDK | -[MessageQueueBySqlite getFirstRecords:withType:] + 1072
10 SensorsAnalyticsSDK | -[SensorsAnalyticsSDK flushByType:flushSize:] + 100
11 SensorsAnalyticsSDK | -[SensorsAnalyticsSDK _flush:] + 180
12 libdispatch.dylib | __dispatch_call_block_and_release + 24
13 libdispatch.dylib | __dispatch_client_callout + 16
14 libdispatch.dylib | __dispatch_queue_serial_drain + 928
15 libdispatch.dylib | __dispatch_queue_invoke + 652
16 libdispatch.dylib | __dispatch_queue_override_invoke + 360
17 libdispatch.dylib | __dispatch_root_queue_drain + 572
18 libdispatch.dylib | __dispatch_worker_thread3 + 124
19 libsystem_pthread.dylib | _pthread_wqthread + 1288

**Comment by minchaozhang** [comment]
你好，感谢反馈。

能提供完整 crash 堆栈信息吗？

**Comment by kinarobin** [comment]
这个看似是苹果系统的bug:

[https://forums.developer.apple.com/thread/63546](https://forums.developer.apple.com/thread/63546)
