### ISSUE TITLE
-JSONSerializableObjectForObject crash, SIGSEGV  SEGV_ACCERR

### ISSUE THREAD

**Issue by Quanhua-Guan** [sensorsdata/sa-sdk-ios#48]
https://github.com/sensorsdata/sa-sdk-ios/blob/b2ecc0e2e153699a18a453dd350a8d1461148e19/SensorsAnalyticsSDK/SAJSONUtil.m#L76

https://github.com/sensorsdata/sa-sdk-ios/blob/b2ecc0e2e153699a18a453dd350a8d1461148e19/SensorsAnalyticsSDK/SAJSONUtil.m#L104

JSONSerializableObjectForObject这个函数中有几处不太合理的代码. 应该使用newObj, 而不是obj. 问题代码会导致野指针崩溃, 不过概率较低.

**Comment by wenquanlebao** [comment]
感谢您的关注和反馈，我们会在后续版本尽快修复~

**Comment by minchaozhang** [comment]
感谢您的反馈，该问题已修复。
