### ISSUE TITLE
UIPageControl 采集的 $AppClick 事件，未采集 $element_content

### ISSUE THREAD

**Issue by wenquanlebao** [sensorsdata/sa-sdk-ios#49]
UIPageControl 采集的 $AppClick 事件，$element_content 属性未采集，可以考虑采集 currentPage 作为 $element_content 属性。

**Comment by yaoyue** [comment]
新增支持并上线，v1.11.17 及以上可以支持

**Comment by wenquanlebao** [comment]
经过测试，v1.11.17 及以上可以支持
