### ISSUE TITLE
不符合Apple开发人员计划许可协议和应用的第3.3.2节商店审查指南2.5.2

### ISSUE THREAD

**Issue by DingSoung** [sensorsdata/sa-sdk-ios#5]
你好，我使用了你们的SDK，仅仅初始化，未埋点，Apple审核上线几天后，收到违反政策通知，并要求下次更新移除，不知道有什么办法规避。下面是通知详情

Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. 

This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

Best regards,

App Store Review

**Comment by wangzhzh** [comment]
Hi，
这个应该不是我们的问题，此次苹果重点审查包含热更新的app，目前我们的iOS SDK里布包含热更新相关代码。

**Comment by wangzhzh** [comment]
我们会进一步确认

**Comment by fullsing** [comment]
我们用了你们的sdk，同样收到苹果的邮件，请问你们什么时候可以解决？如果解决了，能否同步下信息呢？着急等呢？

**Comment by wangzhzh** [comment]
请问你们使用jspatch了吗？

**Comment by DingSoung** [comment]
@wangzhzh 我没有使用任何热修复SDK

**Comment by fullsing** [comment]
我们就只用了你们的sdk，其它都没有用

**Comment by wangzhzh** [comment]
Hi,
你们分别是哪家客户？
可以加我微信或者电话联系：18610277013

**Comment by fullsing** [comment]
你们的可视化统计是不是有下发代码？

**Comment by wangzhzh** [comment]
会从服务端拉取一个config，这个config里主要是可视化埋点控件的信息

**Comment by fullsing** [comment]
怎么能够把可视化的下发代码去掉？

**Comment by fullsing** [comment]
你们的能让审核通过么？有没有能让审核通过的方案？

**Comment by wangzhzh** [comment]
我们本地已经整理出一个去掉可视化埋点代码的版本，由于目前还没有100%确定会因为可视化埋点导致审核被拒，所以目前只支持以源码的方式集成这个版本，一旦确定，我们会立即push到pod上。如果有需要，可以联系我获取源码。

**Comment by DingSoung** [comment]
@wangzhzh  可以先把那个去掉可视化埋点的版本拿出来看看吗，我们共同研究研究。目前我的发版也因此delay了，希望尽快解决

**Comment by wangzhzh** [comment]
[SensorsAnalyticsSDK.zip](https://github.com/sensorsdata/sa-sdk-ios/files/863524/SensorsAnalyticsSDK.zip)

**Comment by DingSoung** [comment]
@wangzhzh   跟我裁剪的结果一样，昨天提交审核试过了，仍然不通过，还是 `method_exchangeImplementations`的问题。可能需要换实现原理奶解决问题

**Comment by wangzhzh** [comment]
你的意思是，还是我们SDK的问题？

**Comment by DingSoung** [comment]
个推问题。
建议核心函数使用SwiftRouter一样的原理。避免今后苹果私有oc这个

**Comment by wangzhzh** [comment]
好的，非常感谢您的建议，我们会继续优化。
