### ISSUE TITLE
v2.0 carthage 编译失败

### ISSUE THREAD

**Issue by cntrump** [sensorsdata/sa-sdk-ios#51]
提示缺少头文件，workspace 里看到很多文件没有被添加到项目里。

**Comment by cntrump** [comment]
另外，扩张的项目设置里，应该去掉签名，设置为 none 才是。

**Comment by cntrump** [comment]
重新新发布的  2.0 版本还是不能编译，一样的问题。

**Comment by minchaozhang** [comment]
> 重新新发布的 2.0 版本还是不能编译，一样的问题。

您好，麻烦提供一下编译环境及报错原因。

**Comment by cntrump** [comment]
Xcode 11.3.1 + Carthage ，直接 Xcode 打开项目编译也会报错，试一下？

**Comment by minchaozhang** [comment]
> Xcode 11.3.1 + Carthage ，直接 Xcode 打开项目编译也会报错，试一下？

您好，我们在不同的机器上进行测试，编译都是没有问题的，麻烦查看是否网络原因导致 Carthage checkout 项目时失败导致的。或者把报错的详细信息提供给我们，再具体排查问题

**Comment by cntrump** [comment]
> > Xcode 11.3.1 + Carthage ，直接 Xcode 打开项目编译也会报错，试一下？
> 
> 您好，我们在不同的机器上进行测试，编译都是没有问题的，麻烦查看是否网络原因导致 Carthage checkout 项目时失败导致的。或者把报错的详细信息提供给我们，再具体排查问题

直接打开 workspace 进行编译就报错了：

```log
In file included from ./Carthage/Checkouts/sa-sdk-ios/SensorsAnalyticsSDK/SensorsAnalyticsSDK.m:70:
./Carthage/Checkouts/sa-sdk-ios/SensorsAnalyticsSDK/SAAuxiliaryToolManager.h:10:9: fatal error: 'SAVisualizedAutoTrackConnection.h' file not found
#import "SAVisualizedAutoTrackConnection.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by cntrump** [comment]
知道怎么回事了，我是 carthage update 更新的，就会报错。
删掉后再重新 carthage update 就正常了。
