### ISSUE TITLE
上传苹果审核 无法通过，原因可能是：sdk内含uiwebview

### ISSUE THREAD

**Issue by iOScodeYF** [sensorsdata/sa-sdk-ios#56]
命令行工具：cd 项目文件夹     grep -r UIWebView .       ./ios/Pods/SensorsAnalyticsSDK/SensorsAnalyticsSDK/SensorsAnalyticsSDK.m:#error disable UIWebView and use WKWebView, minimum deployment target is 8.0
./ios/Pods/SensorsAnalyticsSDK/SensorsAnalyticsSDK/SensorsAnalyticsSDK.m:        UIWebView *webView = [[UIWebView alloc] initWithFrame:CGRectZero];
./ios/Pods/SensorsAnalyticsSDK/SensorsAnalyticsSDK/SensorsAnalyticsSDK.m:        NSAssert(![webView isKindOfClass:NSClassFromString(@"UIWebView")], @"当前集成方式已禁用 UIWebView！❌");

**Comment by minchaozhang** [comment]
我们所有与 `UIWebView` 相关的的 API 都可以使用预编译宏（`SENSORS_ANALYTICS_DISABLE_UIWEBVIEW `）禁用，详细使用方法可以参考官方文档：[预编译宏配置SDK特性](https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_ios_super-1573998.html#id-.SDKAPI(iOS)v1.13-预编译宏配置SDK特性)

**Comment by minchaozhang** [comment]
了解一下，之前不能通过审核的问题解决了吗？
