### ISSUE TITLE
sa-sdk-ios 被bugly 卡顿检测

### ISSUE THREAD

**Issue by aiquantong** [sensorsdata/sa-sdk-ios#60]
最近公司上线bugly的卡顿检测功能，显示sa-sdk-ios会触发卡顿，而且量不少
sa-sdk-ios version: 2.1.4
iOS : 12.3.1

[https://zhaotu.me/image/lCB4E](https://zhaotu.me/image/lCB4E)

对应的code为

3 libdispatch.dylib | 0x00000001ae630000 + 67068
-- | --
4 libdispatch.dylib | 0x00000001ae630000 + 66052
5 ShihuoIPhone | -[SensorsAnalyticsSDK applicationWillTerminateNotification:] (SensorsAnalyticsSDK.m:2701)
6 CoreFoundation | 0x00000001ae860000 + 563236
7 CoreFoundation | 0x00000001ae860000 + 563316

代码如下：
`
- (void)applicationWillTerminateNotification:(NSNotification *)notification {
    SALogDebug(@"applicationWillTerminateNotification");
    dispatch_sync(self.serialQueue, ^{});
}
`
是否可以优化一下

**Comment by yaoyue** [comment]
您好，这里是在 App 即将被 kill  的时候（比如用双击上滑强杀 App），使用 dispatch_sync 的方式，在当前线程卡住 SDK 内的 serialQueue 串行队列，为了确保 serialQueue 这个串行队列内的异步任务执行完毕，从而可以完成采集 App 退出事件，保证事件不丢失。
所以这里的同步任务，只是为了确保事件采集，不影响您这边 App 的业务逻辑。后期可能会考虑优化，目前给您带来不便，希望见谅 ~

**Comment by aiquantong** [comment]
好的 谢谢
