### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by yusheng00** [sensorsdata/sa-sdk-ios#62]
0  CoreFoundation                 0x1a69ae5ac __exceptionPreprocess
1  libobjc.A.dylib                0x1baa2842c objc_exception_throw
2  CoreFoundation                 0x1a68b71b4 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x1a7c157bc -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x1a8b1b480 -[UINavigationController _popNavigationBar:item:]
5  UIKitCore                      0x1a888a42c -[UINavigationBar _sendNavigationPopForBackBarButtonItem:]
6  UIKitCore                      0x1a88b5960 -[_UINavigationBarContentView __backButtonAction:]
7  UIKitCore                      0x1a92cf5a0 -[UIApplication sendAction:to:from:forEvent:]
8  SensorsAnalyticsSDK            0x109df4b10 -[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] + 78 (UIApplication+AutoTrack.m:78)
9  UIKitCore                      0x1a8c2d8d4 -[UIControl sendAction:to:forEvent:]
10 UIKitCore                      0x1a8c2dc28 -[UIControl _sendActionsForEvents:withEvent:]
11 UIKitCore                      0x1a8c2dc78 -[UIControl _sendActionsForEvents:withEvent:]
12 UIKitCore                      0x1a8c2c4f8 -[UIControl touchesEnded:withEvent:]
13 UIKitCore                      0x1a8e24de8 _UIGestureEnvironmentUpdate
14 CoreFoundation                 0x1a692a444 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
15 CoreFoundation                 0x1a6924858 __CFRunLoopDoObservers
16 CoreFoundation                 0x1a6924e08 __CFRunLoopRun
17 CoreFoundation                 0x1a69244bc CFRunLoopRunSpecific
18 GraphicsServices               0x1bd3a9820 GSEventRunModal
19 UIKitCore                      0x1a92c8734 -[UIApplication _run]
20 UIKitCore                      0x1a92cde10 UIApplicationMain

**Comment by minchaozhang** [comment]
从堆栈信息来看，与 SDK 关系不是特别大，建议检查一下相关页面 pop 时的业务逻辑或者页面跳转逻辑是否有问题。
