### ISSUE TITLE
iOS14.3 ipad crash

### ISSUE THREAD

**Issue by CodingQ** [sensorsdata/sa-sdk-ios#63]
1 libobjc.A.dylib | objc_exception_throw + 56
-- | --
2 Foundation | 0x00000001a037d000 + 166048
3 Foundation | 0x00000001a037d000 + 329052
4 UIFoundation | 0x00000001a7d3d000 + 680640
5 UIFoundation | 0x00000001a7d3d000 + 679820
6 UIFoundation | 0x00000001a7d3d000 + 88844
7 UIFoundation | 0x00000001a7d3d000 + 111004
8 UIKitCore | 0x00000001a0f26000 + 15038036
9 Foundation | 0x00000001a037d000 + 615436
10 Foundation | 0x00000001a037d000 + 606492
11 UIKit | 0x00000001e7890000 + 69460
12 UIKitCore | 0x00000001a0f26000 + 14534216
13 UIKitCore | 0x00000001a0f26000 + 11751452
14 SensorsAnalyticsSDK | -[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] + 368
15 UIKitCore | 0x00000001a0f26000 + 1180728
16 TextInputUI | 0x00000001a6dcc000 + 235828
17 UIKitCore | 0x00000001a0f26000 + 11751452
18 SensorsAnalyticsSDK | -[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] + 368

手机项目运行正常,ipad启动时就会出现crash

**Comment by minchaozhang** [comment]
麻烦提供以下信息：
1. SDK 版本
2. 完整的解析后的堆栈信息
感谢您的配合。
