### ISSUE TITLE
Signed integer overflow: 2112820162 * 31 cannot be represented in type 'int'

### ISSUE THREAD

**Issue by qiaomenzhuan** [sensorsdata/sa-sdk-ios#64]
NSString+HashCode.m文件里- (int)sensorsdata_hashCode方法int溢出，换成longlong类型吧

**Comment by minchaozhang** [comment]
这里是与后端 Java 中的算法保持一致，此处即使溢出对于结果没有什么影响。

**Comment by qiaomenzhuan** [comment]
> 这里是与后端 Java 中的算法保持一致，此处即使溢出对于结果没有什么影响。

有影响，Xcode会报一个紫色的感叹号，然后手机页面会明显卡顿一下 ，麻烦优化下。

**Comment by minchaozhang** [comment]
> > 这里是与后端 Java 中的算法保持一致，此处即使溢出对于结果没有什么影响。
> 
> 有影响，Xcode会报一个紫色的感叹号，然后手机页面会明显卡顿一下 ，麻烦优化下。

Xcode 的静态分析确实会出现感叹号。不过手机页面卡顿和此处的代码没有关系，可能是其他的原因导致的。可以将应用启动时的一些操作发出来，一起分析一下。

**Comment by qiaomenzhuan** [comment]
> > > 这里是与后端 Java 中的算法保持一致，此处即使溢出对于结果没有什么影响。
> > 
> > 
> > 有影响，Xcode会报一个紫色的感叹号，然后手机页面会明显卡顿一下 ，麻烦优化下。
> 
> Xcode 的静态分析确实会出现感叹号。不过手机页面卡顿和此处的代码没有关系，可能是其他的原因导致的。可以将应用启动时的一些操作发出来，一起分析一下。

只要有上传事件，控制台打印int溢出错误信息时明显会阻断当前用户操作（正在滑动页面浏览内容），最直观的感受就是页面卡顿了1s左右，当然每次启动应用后只会出现一次这种情况。

**Comment by minchaozhang** [comment]
使用下面的代码，在 Xcode 12.3 上运行，控制台中没有出现 int 溢出信息。您能将那边 Xcode 在控制台中打印的信息发出来看一下吗？

```   
    int a = 0;
    NSLog(@"a: %d", a);
    a = INTMAX_MAX;
    NSLog(@"a: %d", a);
```

**Comment by qiaomenzhuan** [comment]
![截屏2021-03-30 下午3 44 51](https://user-images.githubusercontent.com/17446919/112952774-711c2780-916f-11eb-94de-fbd8a22307bc.png)

**Comment by minchaozhang** [comment]
上传事件是由 SDK 创建的单独线程执行的，不会影响页面跳转刷新。此处溢出警告不影响 App 的正常运行。
