### ISSUE TITLE
-[SANetwork URLSession:task:didFinishCollectingMetrics:]: unrecognized selector sent to instance 0x1700936a0崩溃

### ISSUE THREAD

**Issue by anyuechao** [sensorsdata/sa-sdk-ios#65]
崩溃堆栈信息
1CoreFoundation0x1816751b8___exceptionPreprocess + 124
2libobjc.A.dylib0x1800ac55cobjc_exception_throw
3CoreFoundation0x18167c268___methodDescriptionForSelector + 0
4CoreFoundation0x181679070____forwarding___ + 404
5CoreFoundation0x18157280c___forwarding_prep_0___ + 92
6CFNetwork0x181e424bc___68-[NSURLSession delegate_task:didFinishCollectingMetrics:completion:]_block_invoke + 36
7Foundation0x182163fb0___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
8Foundation0x1820a8aa8-[NSBlockOperation main] + 96
9Foundation0x1820990a4-[__NSOperationInternal _start:] + 620
10Foundation0x18216635c___NSOQSchedule_f + 228
11libdispatch.dylib0x1804fe1bc__dispatch_client_callout + 16
12libdispatch.dylib0x18050c3dc__dispatch_queue_serial_drain + 928
13libdispatch.dylib0x1805019a4__dispatch_queue_invoke + 652
14libdispatch.dylib0x18050e34c__dispatch_root_queue_drain + 572
15libdispatch.dylib0x18050e0ac__dispatch_worker_thread3 + 124
16libsystem_pthread.dylib0x1807072a0__pthread_wqthread + 1288
17libsystem_pthread.dylib0x180706d8c_start_wqthread + 4
主线程

格式化
1libobjc.A.dylib0x1800b1dc8<redacted>
2libsystem_malloc.dylib0x180688be8_nano_calloc + 80
3libsystem_malloc.dylib0x18067a168_malloc_zone_calloc + 152
4libsystem_malloc.dylib0x18067a0ac_calloc + 40
5libobjc.A.dylib0x1800a9cfc<redacted>
6libobjc.A.dylib0x1800aa1fc<redacted>
7libobjc.A.dylib0x1800b4d44<redacted>
8libobjc.A.dylib0x1800bf298<redacted>
9UIAccessibility0x18dd0ccdc<redacted>
10libdispatch.dylib0x1804fe1fc__dispatch_call_block_and_release + 24
11libdispatch.dylib0x1804fe1bc__dispatch_client_callout + 16
12libdispatch.dylib0x180502d68__dispatch_main_queue_callback_4CF + 1000
13CoreFoundation0x181622810___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14CoreFoundation0x1816203fc___CFRunLoopRun + 1660
15CoreFoundation0x18154e2b8_CFRunLoopRunSpecific + 444
16GraphicsServices0x183002198_GSEventRunModal + 180
17UIKit0x1875957fc-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 744
18UIKit0x187590534-[UIStatusBarServer setStatusBar:] + 28
19中国搜索0x100043d0c_main (AppDelegate.swift:34)
20libdyld.dylib0x1805315b8_start + 4

![截屏2021-01-21 下午4 02 17](https://user-images.githubusercontent.com/14137536/105321144-0b0ca480-5c02-11eb-8c21-68675efa8aea.png)

**Comment by minchaozhang** [comment]
您好，从提供的堆栈信息来看，并没有涉及 SANetwork 相关的崩溃，能否提供完整的堆栈信息给我们进行详细分析呢？
