### ISSUE TITLE
APP启动初始化SDK时弱网环境有时会卡在启动页3秒

### ISSUE THREAD

**Issue by qiaomenzhuan** [sensorsdata/sa-sdk-ios#66]
SAEventTracker.m文件里的
- (void)trackEvent:(NSDictionary *)event isSignUp:(BOOL)isSignUp;函数下的
[self.eventStore insertRecord:record];方法启动应用时会阻塞主线程，打开手机设置里开发者的弱网调试会更加明显（启动应用弱网有时会停在启动页3秒）影响启动速度用户体验。
注释掉这行代码不会出现阻塞的情况。
怀疑是sqlite数据库相关操作引起的。麻烦优化下

**Comment by minchaozhang** [comment]
您好，`- (void)trackEvent:(NSDictionary *)event isSignUp:(BOOL)isSignUp` 方法被调用的地方都是在 SDK 中创建的一个单独的线程中执行的，可以通过断点查看当前执行的线程。

关于启动卡顿的问题，是否可以将 SDK 初始化的代码贴出来一起分析探讨一下？

**Comment by qiaomenzhuan** [comment]
n
