### ISSUE TITLE
out of bounds  crash on my app

### ISSUE THREAD

**Issue by S-Freedom** [sensorsdata/sa-sdk-ios#69]
#0 Thread

NSRangeException

NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds

解析原始
0 CoreFoundation	___exceptionPreprocess + 216
1 libobjc.A.dylib	objc_exception_throw + 56
2 Foundation	-[NSAttributedString enumerateAttributesInRange:options:usingBlock:]
3 Foundation	-[NSConcreteMutableAttributedString replaceCharactersInRange:withAttributedString:] + 284
4 UIFoundation	0x00000001adac5000 + 680640
5 UIFoundation	0x00000001adac5000 + 679820
6 UIFoundation	0x00000001adac5000 + 88844
7 UIFoundation	0x00000001adac5000 + 111004
8 UIKitCore	-[_UITextUndoOperationReplace undoRedo] + 416
9 Foundation	-[_NSUndoStack popAndInvoke] + 184
10 Foundation	-[NSUndoManager undoNestedGroup] + 288
11 UIKitCore	-[UISystemDefaultTextInputAssistantItem performSystemButtonActionForStyle:] + 600
12 UIKitCore	-[UIApplication sendAction:to:from:forEvent:] + 96
13 ***	-[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] (UIApplication+AutoTrack.m:70)
14 UIKitCore	-[UIBarButtonItem _triggerActionForEvent:] + 176
15 TextInputUI	0x00000001acb54000 + 235828
16 UIKitCore	-[UIApplication sendAction:to:from:forEvent:] + 96
17 ***	-[UIApplication(AutoTrack) sa_sendAction:to:from:forEvent:] (UIApplication+AutoTrack.m:70)
18 UIKitCore	-[UIControl sendAction:to:forEvent:] + 240

**Comment by minchaozhang** [comment]
这个看起来像是 App 里处理字符串时出现的崩溃，好像和 SDK 关系不大。可以放上完整的堆栈信息一起分析一下。
