### ISSUE TITLE
推送相关的ID写反了

### ISSUE THREAD

**Issue by gongruike** [sensorsdata/sa-sdk-ios#7]
1.6.39版本SensorsAnalyticsSDK.m文件第55行和56行好像写反了。

`NSString* const APP_PUSH_ID_PROPERTY_GETUI = @"$app_push_id_xiaomi";

NSString* const APP_PUSH_ID_PROPERTY_XIAOMI = @"$app_push_id_getui";`

![image](https://cloud.githubusercontent.com/assets/4476750/25174425/e51d6484-2529-11e7-9966-4c5d75548d0d.png)

**Comment by wangzhzh** [comment]
非常感谢，我们尽快修复!

**Comment by huangzhifei** [comment]
这个会影响埋点上报功能吗？

发自我的 iPhone

**Comment by wangzhzh** [comment]
不会，这几行代码完全没有用处，是之前做的推送遗留下来的代码片段，最新版本已删除。
