### ISSUE TITLE
请问有针对iOS14.5隐私权限AppTrackingTransparency的适配么

### ISSUE THREAD

**Issue by LynahZ** [sensorsdata/sa-sdk-ios#70]

**Comment by minchaozhang** [comment]
可以参考官方说明：https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_compliance-22252691.html

**Comment by LynahZ** [comment]
> 可以参考官方说明：https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_compliance-22252691.html

感谢，但是由于有其他SDK使用AdSupport.framework且必须保留的情况下，需要在神策SDK获取idfa时先进行ATTrackingManager的权限获取么

**Comment by minchaozhang** [comment]
如果使用渠道相关的功能，可以通过获取 IDFA 实现精准匹配。如果没有则可以不获取，不影响 SDK 的功能。
