### ISSUE TITLE
关于 2.2.7 以后 SAReachability.m 文件 导致的编译报错

### ISSUE THREAD

**Issue by pepsikirk** [sensorsdata/sa-sdk-ios#71]
SAReachability.m 文件
在 2.2.7 版本中是

> #import <netinet/in.h>

之后的版本改成了

> #if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 90000)
> #import <netinet6/in6.h>
> #else
> #import <netinet/in.h>
> #endif
> 

会在最新的 Xcode 12.4 编译报错

![image](https://user-images.githubusercontent.com/7042430/115549788-9ff36c80-a2db-11eb-8e5f-1f2c20d4a9bd.png)

手动修改为

> #import <netinet/in.h>
> #import <netinet6/in6.h>

是可以正常编译通过的。在 AFNetworking 的 AFHTTPSessionManager.m 和 AFNetworkReachabilityManager.m 中都是这样引入的。
我已经等了3个月的时间你们都没有更新修复，希望你们能够尽快更新修复

**Comment by minchaozhang** [comment]
您好，我们在 Xcode 12.4 中，无论使用什么样的配置均未出现编译报错的情况。能否提供一下你们 App 支持的最小版本，以及是否有其他库引入类似网络监听功能。

**Comment by pepsikirk** [comment]
> 您好，我们在 Xcode 12.4 中，无论使用什么样的配置均未出现编译报错的情况。能否提供一下你们 App 支持的最小版本，以及是否有其他库引入类似网络监听功能。

最小支持版本为 iOS 9，其它类似的库有 AFNetworking 和 ZFPlayer ，都可以正常编译

**Comment by minchaozhang** [comment]
> 最小支持版本为 iOS 9，其它类似的库有 AFNetworking 和 ZFPlayer ，都可以正常编译

新建一个项目，使用下面的配置，编译是成功了的。

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for Example
  pod 'SensorsAnalyticsSDK'
  pod 'ZFPlayer'
  pod 'AFNetworking'
end

```

您项目那边有引入或者实现过单独的 netinet 函数库吗？或者有没有定义过 socklen_t 函数

**Comment by pepsikirk** [comment]
> > 最小支持版本为 iOS 9，其它类似的库有 AFNetworking 和 ZFPlayer ，都可以正常编译
> 
> 新建一个项目，使用下面的配置，编译是成功了的。
> 
> ```
> # Uncomment the next line to define a global platform for your project
> platform :ios, '9.0'
> 
> target 'Example' do
>   # Comment the next line if you don't want to use dynamic frameworks
> #  use_frameworks!
> 
>   # Pods for Example
>   pod 'SensorsAnalyticsSDK'
>   pod 'ZFPlayer'
>   pod 'AFNetworking'
> end
> ```
> 
> 您项目那边有引入或者实现过单独的 netinet 函数库吗？或者有没有定义过 socklen_t 函数

明天我试一下用demo

**Comment by minchaozhang** [comment]
我们近期会发版，修改为：
```
#import <netinet/in.h>
#import <netinet6/in6.h>
```
但是其实我们并不知道什么样的配置会导致编译报错的问题，您那边如果弄清了问题原因，可以跟我们反馈一下，感谢。

**Comment by pepsikirk** [comment]
> 我们近期会发版，修改为：
> 
> ```
> #import <netinet/in.h>
> #import <netinet6/in6.h>
> ```
> 
> 但是其实我们并不知道什么样的配置会导致编译报错的问题，您那边如果弄清了问题原因，可以跟我们反馈一下，感谢。

我这边测试得到结果了，是因为我们项目使用了 CCache ，所以将所以的第三方库的 CLANG_ENABLE_MODULES 关闭了，开启后是可以编译成功的。
看来是因为关闭了 CLANG_ENABLE_MODULES ，所以没不能因为 import <netinet6/in6.h> 而自动 import <netinet6/in6.h>
所以确实是应该你们修改。

**Comment by pepsikirk** [comment]
经过测试最新版已经可以编译成功，故关闭此issue。

**Comment by minchaozhang** [comment]
感谢反馈~有任何问题都可以提 issue
