### ISSUE TITLE
runtime error: signed integer overflow: 2112820162 * 31 cannot be represented in type 'int'

### ISSUE THREAD

**Issue by pikacode** [sensorsdata/sa-sdk-ios#72]
你好，我使用了贵公司的SDK，在 debug 时总会出现 runtime error，每次都会卡住 Xcode 和 模拟器 10 秒左右的时间，麻烦修复一下这个问题

![企业微信20210422-143306](https://user-images.githubusercontent.com/12589575/115667080-fca46500-a377-11eb-9cfc-86d04cd344f8.png)

**Comment by minchaozhang** [comment]
https://github.com/sensorsdata/sa-sdk-ios/issues/64
