### ISSUE TITLE
在4G网络下，SAEventTracker的-flushRecordsWithSize:连续多次请求，方法中dispatch_sync(strongSelf.queue, block);会引起APP卡住（卡死 页面不再响应事件），如下面描述中的写法网络请求回主线程dispatch_async(dispatch_get_main_queue(), ^{});在使用WiFi网络时，是正常的...

### ISSUE THREAD

**Issue by AaronZhao13** [sensorsdata/sa-sdk-ios#73]
复现路径描述：
在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。

可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现

打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。

// flush
    __weak typeof(self) weakSelf = self;
    [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
        __strong typeof(weakSelf) strongSelf = weakSelf;
        void(^block)(void) = ^ {
            if (!success) {
                [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
                return;
            }
            // 5. 删除数据
            if ([strongSelf.eventStore deleteRecords:recordIDs]) {
                [strongSelf flushRecordsWithSize:size];
            }
        };
        if (sensorsdata_is_same_queue(strongSelf.queue)) {
            block();
        } else {
            dispatch_sync(strongSelf.queue, block);
        }
    }];
// 网络请求
- (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
    __block BOOL flushSuccess = NO;
    // 当在程序终止或 debug 模式下，使用线程锁
    BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
    [self requestWithRecords:records completion:^(BOOL success) {
//        if (isWait) {
//            flushSuccess = success;
//            dispatch_semaphore_signal(self.flushSemaphore);
//        } else {
        dispatch_async(dispatch_get_main_queue(), ^{
            completion(success);
        });
//        }
    }];
//    if (isWait) {
//        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
//        completion(flushSuccess);
//    }
}

**Comment by LuckinDog** [comment]
> 复现路径描述：
> 在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。
> 
> 可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现
> 
> 打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。
> 
> // flush
> __weak typeof(self) weakSelf = self;
> [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
> __strong typeof(weakSelf) strongSelf = weakSelf;
> void(^block)(void) = ^ {
> if (!success) {
> [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
> return;
> }
> // 5. 删除数据
> if ([strongSelf.eventStore deleteRecords:recordIDs]) {
> [strongSelf flushRecordsWithSize:size];
> }
> };
> if (sensorsdata_is_same_queue(strongSelf.queue)) {
> block();
> } else {
> dispatch_sync(strongSelf.queue, block);
> }
> }];
> // 网络请求
> 
> * (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
>   __block BOOL flushSuccess = NO;
>   // 当在程序终止或 debug 模式下，使用线程锁
>   BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
>   [self requestWithRecords:records completion:^(BOOL success) {
>   //        if (isWait) {
>   //            flushSuccess = success;
>   //            dispatch_semaphore_signal(self.flushSemaphore);
>   //        } else {
>   dispatch_async(dispatch_get_main_queue(), ^{
>   completion(success);
>   });
>   //        }
>   }];
>   //    if (isWait) {
>   //        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
>   //        completion(flushSuccess);
>   //    }
>   }

你好，我们的 flushRecordsWithSize 接口是不对外暴露的，您说的 “可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传”指的是什么意思，连续点击 button 触发了 flushRecordsWithSize 还是说，你通过修改源码，让 flushRecordsWithSize 暴露出来，在点击 button 时外部调用 flushRecordsWithSize？

**Comment by AaronZhao13** [comment]
> > 复现路径描述：
> > 在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。
> > 可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现
> > 打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。
> > // flush
> > __weak typeof(self) weakSelf = self;
> > [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
> > __strong typeof(weakSelf) strongSelf = weakSelf;
> > void(^block)(void) = ^ {
> > if (!success) {
> > [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
> > return;
> > }
> > // 5. 删除数据
> > if ([strongSelf.eventStore deleteRecords:recordIDs]) {
> > [strongSelf flushRecordsWithSize:size];
> > }
> > };
> > if (sensorsdata_is_same_queue(strongSelf.queue)) {
> > block();
> > } else {
> > dispatch_sync(strongSelf.queue, block);
> > }
> > }];
> > // 网络请求
> > 
> > * (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
> >   __block BOOL flushSuccess = NO;
> >   // 当在程序终止或 debug 模式下，使用线程锁
> >   BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
> >   [self requestWithRecords:records completion:^(BOOL success) {
> >   //        if (isWait) {
> >   //            flushSuccess = success;
> >   //            dispatch_semaphore_signal(self.flushSemaphore);
> >   //        } else {
> >   dispatch_async(dispatch_get_main_queue(), ^{
> >   completion(success);
> >   });
> >   //        }
> >   }];
> >   //    if (isWait) {
> >   //        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
> >   //        completion(flushSuccess);
> >   //    }
> >   }
> 
> 你好，我们的 flushRecordsWithSize 接口是不对外暴露的，您说的 “可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传”指的是什么意思，连续点击 button 触发了 flushRecordsWithSize 还是说，你通过修改源码，让 flushRecordsWithSize 暴露出来，在点击 button 时外部调用 flushRecordsWithSize？

大概意思是连续多次执行埋点数据上传的操作，加个按钮，跑demo复现的时候比较好操作一些。上传请求-flushEventRecords:completion:的block回调添加回主线程操作。出现APP卡住不动的问题，应该是修改了-flushEventRecords:completion:回调会主线程引起的。

**Comment by LuckinDog** [comment]
> > > 复现路径描述：
> > > 在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。
> > > 可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现
> > > 打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。
> > > // flush
> > > __weak typeof(self) weakSelf = self;
> > > [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
> > > __strong typeof(weakSelf) strongSelf = weakSelf;
> > > void(^block)(void) = ^ {
> > > if (!success) {
> > > [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
> > > return;
> > > }
> > > // 5. 删除数据
> > > if ([strongSelf.eventStore deleteRecords:recordIDs]) {
> > > [strongSelf flushRecordsWithSize:size];
> > > }
> > > };
> > > if (sensorsdata_is_same_queue(strongSelf.queue)) {
> > > block();
> > > } else {
> > > dispatch_sync(strongSelf.queue, block);
> > > }
> > > }];
> > > // 网络请求
> > > 
> > > * (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
> > >   __block BOOL flushSuccess = NO;
> > >   // 当在程序终止或 debug 模式下，使用线程锁
> > >   BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
> > >   [self requestWithRecords:records completion:^(BOOL success) {
> > >   //        if (isWait) {
> > >   //            flushSuccess = success;
> > >   //            dispatch_semaphore_signal(self.flushSemaphore);
> > >   //        } else {
> > >   dispatch_async(dispatch_get_main_queue(), ^{
> > >   completion(success);
> > >   });
> > >   //        }
> > >   }];
> > >   //    if (isWait) {
> > >   //        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
> > >   //        completion(flushSuccess);
> > >   //    }
> > >   }
> > 
> > 
> > 你好，我们的 flushRecordsWithSize 接口是不对外暴露的，您说的 “可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传”指的是什么意思，连续点击 button 触发了 flushRecordsWithSize 还是说，你通过修改源码，让 flushRecordsWithSize 暴露出来，在点击 button 时外部调用 flushRecordsWithSize？
> 
> 大概意思是连续多次执行埋点数据上传的操作，加个按钮，跑demo复现的时候比较好操作一些。上传请求-flushEventRecords:completion:的block回调添加回主线程操作。出现APP卡住不动的问题，应该是修改了-flushEventRecords:completion:回调会主线程引起的。

您好，修改 -flushEventRecords:completion:的block 的回调添加回主线程的操作，我们这边测试时发现的确会卡住主线程，我们这边一般是不建议直接修改源码的，您是神策这边的客户吗？修改这个操作是因为什么原因？如果是因为特殊的场景需求，可以在我们的技术对接群里面反馈下。

**Comment by AaronZhao13** [comment]
> > > > 复现路径描述：
> > > > 在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。
> > > > 可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现
> > > > 打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。
> > > > // flush
> > > > __weak typeof(self) weakSelf = self;
> > > > [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
> > > > __strong typeof(weakSelf) strongSelf = weakSelf;
> > > > void(^block)(void) = ^ {
> > > > if (!success) {
> > > > [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
> > > > return;
> > > > }
> > > > // 5. 删除数据
> > > > if ([strongSelf.eventStore deleteRecords:recordIDs]) {
> > > > [strongSelf flushRecordsWithSize:size];
> > > > }
> > > > };
> > > > if (sensorsdata_is_same_queue(strongSelf.queue)) {
> > > > block();
> > > > } else {
> > > > dispatch_sync(strongSelf.queue, block);
> > > > }
> > > > }];
> > > > // 网络请求
> > > > 
> > > > * (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
> > > >   __block BOOL flushSuccess = NO;
> > > >   // 当在程序终止或 debug 模式下，使用线程锁
> > > >   BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
> > > >   [self requestWithRecords:records completion:^(BOOL success) {
> > > >   //        if (isWait) {
> > > >   //            flushSuccess = success;
> > > >   //            dispatch_semaphore_signal(self.flushSemaphore);
> > > >   //        } else {
> > > >   dispatch_async(dispatch_get_main_queue(), ^{
> > > >   completion(success);
> > > >   });
> > > >   //        }
> > > >   }];
> > > >   //    if (isWait) {
> > > >   //        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
> > > >   //        completion(flushSuccess);
> > > >   //    }
> > > >   }
> > > 
> > > 
> > > 你好，我们的 flushRecordsWithSize 接口是不对外暴露的，您说的 “可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传”指的是什么意思，连续点击 button 触发了 flushRecordsWithSize 还是说，你通过修改源码，让 flushRecordsWithSize 暴露出来，在点击 button 时外部调用 flushRecordsWithSize？
> > 
> > 
> > 大概意思是连续多次执行埋点数据上传的操作，加个按钮，跑demo复现的时候比较好操作一些。上传请求-flushEventRecords:completion:的block回调添加回主线程操作。出现APP卡住不动的问题，应该是修改了-flushEventRecords:completion:回调会主线程引起的。
> 
> 您好，修改 -flushEventRecords:completion:的block 的回调添加回主线程的操作，我们这边测试时发现的确会卡住主线程，我们这边一般是不建议直接修改源码的，您是神策这边的客户吗？修改这个操作是因为什么原因？如果是因为特殊的场景需求，可以在我们的技术对接群里面反馈下。

是debug测试时，实时看一下埋点事件存取上传，显示事件数量用的。然后偶然间遇到了这个情况。

**Comment by LuckinDog** [comment]
> > > > > 复现路径描述：
> > > > > 在-(void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion中，在请求成功的时候，执行回主线程的操作。
> > > > > 可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传，复现
> > > > > 打印log的话，会发现是主线程和self.queue之前反复切换，最终APP会卡住。
> > > > > // flush
> > > > > __weak typeof(self) weakSelf = self;
> > > > > [self.eventFlush flushEventRecords:encryptRecords completion:^(BOOL success) {
> > > > > __strong typeof(weakSelf) strongSelf = weakSelf;
> > > > > void(^block)(void) = ^ {
> > > > > if (!success) {
> > > > > [strongSelf.eventStore updateRecords:recordIDs status:SAEventRecordStatusNone];
> > > > > return;
> > > > > }
> > > > > // 5. 删除数据
> > > > > if ([strongSelf.eventStore deleteRecords:recordIDs]) {
> > > > > [strongSelf flushRecordsWithSize:size];
> > > > > }
> > > > > };
> > > > > if (sensorsdata_is_same_queue(strongSelf.queue)) {
> > > > > block();
> > > > > } else {
> > > > > dispatch_sync(strongSelf.queue, block);
> > > > > }
> > > > > }];
> > > > > // 网络请求
> > > > > 
> > > > > * (void)flushEventRecords:(NSArray<SAEventRecord *> *)records completion:(void (^)(BOOL success))completion {
> > > > >   __block BOOL flushSuccess = NO;
> > > > >   // 当在程序终止或 debug 模式下，使用线程锁
> > > > >   BOOL isWait = self.flushBeforeEnterBackground || self.isDebugMode;
> > > > >   [self requestWithRecords:records completion:^(BOOL success) {
> > > > >   //        if (isWait) {
> > > > >   //            flushSuccess = success;
> > > > >   //            dispatch_semaphore_signal(self.flushSemaphore);
> > > > >   //        } else {
> > > > >   dispatch_async(dispatch_get_main_queue(), ^{
> > > > >   completion(success);
> > > > >   });
> > > > >   //        }
> > > > >   }];
> > > > >   //    if (isWait) {
> > > > >   //        dispatch_semaphore_wait(self.flushSemaphore, DISPATCH_TIME_FOREVER);
> > > > >   //        completion(flushSuccess);
> > > > >   //    }
> > > > >   }
> > > > 
> > > > 
> > > > 你好，我们的 flushRecordsWithSize 接口是不对外暴露的，您说的 “可以添加一个按钮，通过连续点击执行-flushRecordsWithSize:进行事件上传”指的是什么意思，连续点击 button 触发了 flushRecordsWithSize 还是说，你通过修改源码，让 flushRecordsWithSize 暴露出来，在点击 button 时外部调用 flushRecordsWithSize？
> > > 
> > > 
> > > 大概意思是连续多次执行埋点数据上传的操作，加个按钮，跑demo复现的时候比较好操作一些。上传请求-flushEventRecords:completion:的block回调添加回主线程操作。出现APP卡住不动的问题，应该是修改了-flushEventRecords:completion:回调会主线程引起的。
> > 
> > 
> > 您好，修改 -flushEventRecords:completion:的block 的回调添加回主线程的操作，我们这边测试时发现的确会卡住主线程，我们这边一般是不建议直接修改源码的，您是神策这边的客户吗？修改这个操作是因为什么原因？如果是因为特殊的场景需求，可以在我们的技术对接群里面反馈下。
> 
> 是debug测试时，实时看一下埋点事件存取上传，显示事件数量用的。然后偶然间遇到了这个情况。
> 应该是回主线程和
> if (sensorsdata_is_same_queue(strongSelf.queue)) {
> block();
> } else {
> dispatch_sync(strongSelf.queue, block);
> }
> 这个切换队列相互占用了。把dispatch_sync改用dispatch_async，或者不回主线程操作是不会卡住的。
> 想了解一下，如果还需要回主线程，同时使用dispatch_async进行异步切换队列是不是就无法保证埋点事件的数据库操作的增 删 改 上传是按顺序执行了？

您好，SDK 目前上传数据策略是选取数据库表中按 id 升序排列的 N 条数据（NSString *query = [NSString stringWithFormat:@"SELECT id,content FROM dataCache WHERE %@ = 0 ORDER BY id ASC LIMIT %lu", kDatabaseColumnStatus, (unsigned long)recordSize];），如果不做 sync 操作，那么在上传和更新、删除时就会有数据重复、错乱的问题发生

**Comment by AaronZhao13** [comment]
> 上传和更新

好的 了解 感谢

**Comment by xunan623** [comment]
问下这个问题是通过什么方式关闭了，是升级版本吗？
