### ISSUE TITLE
carthage build failed on version 2.6.4

### ISSUE THREAD

**Issue by jjksam** [sensorsdata/sa-sdk-ios#74]
*** Building scheme "SensorsAnalyticsExtension" in SensorsAnalyticsSDK.xcworkspace
*** Building scheme "SensorsAnalyticsSDK" in SensorsAnalyticsSDK.xcworkspace
Build Failed
 Task failed with exit code 65:
 /usr/bin/xcrun xcodebuild -workspace /Users/jjk/Documents/rsc_ios/Carthage/Checkouts/sa-sdk-ios/SensorsAnalyticsSDK.xcworkspace -scheme SensorsAnalyticsSDK -configuration Release -derivedDataPath /Users/jjk/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/sa-sdk-ios/v2.6.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l9/0g908fn10bsgjsbvgpc1120c0000gn/T/sa-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/jjk/Documents/rsc_ios/Carthage/Checkouts/sa-sdk-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l9/0g908fn10bsgjsbvgpc1120c0000gn/T/carthage-xcodebuild.foTaTx.log

** ARCHIVE FAILED **

The following build commands failed:
    CompileC /Users/jjk/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/sa-sdk-ios/v2.6.4/Build/Intermediates.noindex/ArchiveIntermediates/SensorsAnalyticsSDK/IntermediateBuildFilesPath/SensorsAnalyticsSDK.build/Release-iphoneos/SensorsAnalyticsSDK.build/Objects-normal/armv7/UIScrollView+AutoTrack.o /Users/jjk/Documents/rsc_ios/Carthage/Checkouts/sa-sdk-ios/SensorsAnalyticsSDK/Core/AutoTrack/Cell/UIScrollView+AutoTrack.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by YQqiang** [comment]
您好，
这边使用 xcodebuild 命令可以正常编译
命令如下所示，和您提供的参数一致
```
/usr/bin/xcrun xcodebuild -workspace /Users/yuqiang/SensorsData/code/SACarthage/Carthage/Checkouts/sa-sdk-ios/SensorsAnalyticsSDK.xcworkspace -scheme SensorsAnalyticsSDK -configuration Release -derivedDataPath /Users/yuqiang/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/sa-sdk-ios/v2.6.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l9/0g908fn10bsgjsbvgpc1120c0000gn/T/sa-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO
```
编译结果
```
Touch /Users/yuqiang/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/sa-sdk-ios/v2.6.4/Build/Intermediates.noindex/ArchiveIntermediates/SensorsAnalyticsSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SensorsAnalyticsSDK.framework (in target 'SensorsAnalyticsSDK' from project 'SensorsAnalyticsSDK')
    cd /Users/yuqiang/SensorsData/code/SACarthage/Carthage/Checkouts/sa-sdk-ios
    /usr/bin/touch -c /Users/yuqiang/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/sa-sdk-ios/v2.6.4/Build/Intermediates.noindex/ArchiveIntermediates/SensorsAnalyticsSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SensorsAnalyticsSDK.framework

** ARCHIVE SUCCEEDED **
```

如果使用 Carthage update 出现如下错误：
```
Build Failed
    Task failed with exit code 1:
    /usr/bin/xcrun lipo -create /Users/rachal/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/sa-sdk-ios/v2.1.10/Build/Intermediates.noindex/ArchiveIntermediates/SensorsAnalyticsSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SensorsAnalyticsSDK.framework/SensorsAnalyticsSDK /Users/rachal/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/sa-sdk-ios/v2.1.10/Build/Products/Release-iphonesimulator/SensorsAnalyticsSDK.framework/SensorsAnalyticsSDK -output /Users/rachal/Desktop/SADemo-Carthage/SADemo/Carthage/Build/iOS/SensorsAnalyticsSDK.framework/SensorsAnalyticsSDK
 
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yn/bhndvnds23773txs7jk8qkq40000gn/T/carthage-xcodebuild.B9PwbC.log
```
可参考 Carthage issue：https://github.com/Carthage/Carthage/issues/3019

您那边还有其他配置项吗？或者您那边用 Xcode 编译是否正常呢？
