### ISSUE TITLE
swift private范型触发死循环

### ISSUE THREAD

**Issue by boboboa32** [sensorsdata/sa-sdk-ios#77]
传递private范性类型给其他模块的vc类会导致findNextViewControllerByResponder死循环
详情见demo
[Demo.zip](https://github.com/sensorsdata/sa-sdk-ios/files/6819862/Demo.zip)

**Comment by minchaozhang** [comment]
感谢您的反馈，我们尽快修复。

**Comment by YQqiang** [comment]
> 传递private范性类型给其他模块的vc类会导致findNextViewControllerByResponder死循环
> 详情见demo
> [Demo.zip](https://github.com/sensorsdata/sa-sdk-ios/files/6819862/Demo.zip)

感谢您的反馈，我们已经在 [v2.6.10](https://github.com/sensorsdata/sa-sdk-ios/releases/tag/v2.6.10) 版本中进行了修复，辛苦使用最新版验证下。
