### ISSUE TITLE
期望增加页面停留时长功能

### ISSUE THREAD

**Issue by gelinxiao** [sensorsdata/sa-sdk-ios#79]

**Comment by Ambitiones** [comment]
关于视图停留时长,我改变了黑名单plist文件的管理机制. 在plist 文件增加了不同期望值的视图类数组.然后在进入视图时,对plist文件查询,对当前视图通过枚举分类.
1. 黑名单Type:    不统计任何数据,直接过滤.
2. 白名单Type:    统计用户停留时长, 即给此类型数据,替换进入/退出视图系统方法,添加trackStart/trackEnd事件实现时长统计.
3. 灵动(名字自己起的)Type: 统计此视图中出现的特定控件(通过添加特定前缀标识)检索数据是否需要统计上报分析.这个方法实现有点繁琐,如果大神有其它好的意见还请不吝赐教.
4. 未在plist文件中管理的视图,被默认执行一次track操作.

希望以上的思路可以帮到你.

**Comment by minchaozhang** [comment]
SDK 已支持页面停留时长统计功能，使用方式参考：https://manual.sensorsdata.cn/sa/latest/sdk-api-ios-22253311.html#id-.SDKAPI(iOS)v1.13-%E9%87%87%E9%9B%86%E9%A1%B5%E9%9D%A2%E6%B5%8F%E8%A7%88%E6%97%B6%E9%95%BF
