### ISSUE TITLE
NSPredicate异常

### ISSUE THREAD

**Issue by everyu** [sensorsdata/sa-sdk-ios#8]
SAObjectSelector 类中的nextFilter方法中 
NSPredicate *parsedPredicate = [NSPredicate predicateWithFormat:predicateFormat];
这一行抛异常，可能是正则语句拼接问题，是不是AND后边少了空格？
log如下：
po predicateFormat
(mp_varB='79b8fa9c1121f57d278e80859874cc05e6a372e5'ANDmp_varC='2e2d8e4253076ca9f32c167995e01787b8bcd8ed')

**Comment by wangzhzh** [comment]
我们看一下

**Comment by wangzhzh** [comment]
Hi,你方便微信沟通吗？

**Comment by wangzhzh** [comment]
确实是我们这边的bug，下一版会修复，非常感谢您～

**Comment by wangzhzh** [comment]
此问题已fix，需要升级后台，SDK无须升级。请知晓～
