### ISSUE TITLE
Crash : '-[UINavigationController sa_autotrack_viewDidAppear:]: unrecognized selector sent to instance 0x7fbe1f01fa00'

### ISSUE THREAD

**Issue by brave723** [sensorsdata/sa-sdk-ios#80]
我项目中引入了Aspects
[UIViewController aspect_hookSelector:@selector(viewDidAppear:) withOptions:AspectPositionAfter usingBlock:^(id<AspectInfo> aspectInfo, BOOL animated) {
  } error:NULL];

通过以上方法hook了 viewdidappear：方法
'-[UINavigationController sa_autotrack_viewDidAppear:]: unrecognized selector sent to instance 0x7fbe1f01fa00'。就报这个crash

**Comment by RachalZhou** [comment]
@brave723 感谢您的反馈。由于 Aspects 实现原理使用消息转发的形式，与普通的 Swizzle 方式冲突，集成 SDK 并使用 Aspects hook viewDidAppear、sendAction 等方法，会导致 Aspects 找不到原始方法，Aspects 会抛出找不到方法的异常。SDK 暂不兼容 Aspects，方便的话请添加 QQ  2141984253 详细沟通。
