### ISSUE TITLE
系统类方法被全部替换掉后,系统类方法被污染的问题

### ISSUE THREAD

**Issue by Ambitiones** [sensorsdata/sa-sdk-ios#86]
我最近看了iOS端SDK的开发集成方案,想请教作者一个问题: 
        全埋点在很大程度上都是通过给系统类添加拓展的方式进行无侵入埋点管理.但是关于 Action点击, 视图跳转,列表点击等可能有的视图不是太需要进行数据统计和上报.关于这个问题我现在是通过给基类派发不同的继承类,然后在继承类的拓展中实现方法交换.以规避父类被事件污染的可能性.想请教下作者有没有什么好的解决办法?

**Comment by cheng-ren** [comment]
从源码的方法交换上来看，交换是交换的UIViewController的viewDidAppear，从整个库的架构思想上来看，没有给留这个口。可以修改源码的方式来实现
1. 交换指定基类的方法（你提到的）
2. 可以在源码中注入Flag，只有遵循某个协议才可以执行交换后的方法里面特定代码（依旧污染，但是可以提高效率）
3. 延缓交换时间，在需要的时候进行交换。

上面都有些麻烦，但是方案很多，自己有需求的话，那就自定义

**Comment by yaoyue** [comment]
如果部分页面或元素类型不需要全埋点采集，您可以参考使用接口进行忽略，参考集成文档：
[事件的忽略与补充](https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_ios_super-1573999.html#id-基础API介绍（iOS）-事件的忽略与补充)
