### ISSUE TITLE
swift 编译不过

### ISSUE THREAD

**Issue by yeguizhong** [sensorsdata/sa-sdk-ios#87]
版本v4.2.0 carthage 执行完 carthage update sa-sdk-ios  --platform iOS --use-xcframeworks，的包编译不过，现在我又用回4.1.5了是正常的，你们检查下最新版本改了啥，商用SDK，发布前认真点

**Comment by minchaozhang** [comment]
您好，使用 Demo 进行了本地验证，未发现问题。

执行 `carthage update --platform iOS --use-xcframeworks` 打印如下日志：
```
*** Cloning sa-sdk-ios
*** Checking out sa-sdk-ios at "v4.2.0"
*** xcodebuild output can be found in /var/folders/8k/3pp4b26j3w934jztfq83t_f80000gn/T/carthage-xcodebuild.3caPKV.log
*** Building scheme "SensorsAnalyticsSDK" in SensorsAnalyticsSDK.xcworkspace
*** Building scheme "SensorsAnalyticsExtension" in SensorsAnalyticsSDK.xcworkspace
```
输出的 framework 集成之后，功能正常。

辛苦，提供一下报错日志，以便排查问题
