### ISSUE TITLE
iOS 13.0 以上系统  工程不含 SceneDelegate的时候   启动时间统计不到

### ISSUE THREAD

**Issue by longfeiwang91** [sensorsdata/sa-sdk-ios#88]
if (@available(iOS 13.0, *)) {
        // iOS 13 及以上在异步主队列的 block 修改状态的原因:
        // 1. 保证在执行启动（被动启动）事件时（动态）公共属性设置完毕（通过监听 UIApplicationDidFinishLaunchingNotification 可以实现）
        // 2. 含有 SceneDelegate 的工程中延迟获取 applicationState 才是准确的（通过监听 UIApplicationDidFinishLaunchingNotification 获取不准确）
        dispatch_async(dispatch_get_main_queue(), mainThreadBlock);
    } else {
        // iOS 13 以下通过监听 UIApplicationDidFinishLaunchingNotification 的通知来处理被动启动和冷启动（非延迟初始化）的情况:
        // 1. iOS 13 以下被动启动时异步主队列的 block 不会执行
        // 2. iOS 13 以下不会含有 SceneDelegate
#if TARGET_OS_IPHONE
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(applicationDidFinishLaunching:)
                                                     name:UIApplicationDidFinishLaunchingNotification
                                                   object:nil];
#endif
        // 处理 iOS 13 以下（冷启动）延迟初始化的情况
        dispatch_async(dispatch_get_main_queue(), mainThreadBlock);
    }

#######################

 if (@available(iOS 13.0, *)) {

里面应该判断  工程是否含 SceneDelegate   不含有的情况下   还是要通过监听

**Comment by minchaozhang** [comment]
您好，请问启动时间是指的 `$AppStart` 事件吗？我们通过测试未发现启动事件采集不到的情况，能否提供一个可复现的 Demo
