### ISSUE TITLE
在SADatabase类的createTable中好像有段遗留代码

### ISSUE THREAD

**Issue by MrKang** [sensorsdata/sa-sdk-ios#93]
在createTable方法中有段逻辑是县创建一个不包含status列的table，然后再去调用-[SADatabase createColumn:inTable:]来修改表结构添加status列，并且这个-[SADatabase createColumn:inTable:]方法名很有迷惑性，看起来是给表添加一个任意列的，但其实方法的第一句就是判断表中是否已经包含status列，如果是则不再执行。所以没有找到为什么要选择先创建表后修改表结构添加列的理由，是不是在创建表的时候就把这个status列创建了会更好

**Comment by minchaozhang** [comment]
感谢您的反馈，这段代码确实有点问题，不过不会影响当前 SDK 的功能。下版本中会修复，感谢关注 SDK。
