### ISSUE TITLE
App Store warning ITMS-90176: Unrecognized Locale 

### ISSUE THREAD

**Issue by longtoken** [sensorsdata/sa-sdk-ios#97]
ITMS-90176: Unrecognized Locale - - The locale names used in localization directories at ( 'Payload/app_name.app/SensorsAnalyticsSDK.bundle/sa_language.lproj' ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories.

麻烦看下，谢谢。

**Comment by wenquanlebao** [comment]
您好，感谢关注我们 SDK 的代码。此问题已经在 v4.3.4 版本修复了，可以更新下 SDK 的版本。
