### ISSUE TITLE
从4.3.4版本开始和三方库冲突

### ISSUE THREAD

**Issue by weizhangCoder** [sensorsdata/sa-sdk-ios#98]
从4.3.4开始和第三方库骨架屏 pod 'TABAnimated', ‘2.6.4’冲突，导致带有骨架屏的UICollectionView 的不能点击cell.

**Comment by minchaozhang** [comment]
TABAnimated 和 RxSwift、Texture 等三方库同样有一定的兼容问题，需要等 TABAnimated 开发者适配

**Comment by weizhangCoder** [comment]
> 

告知了TABAnimated  的作者，但发现TABAnimated 最后一个版本2.6.4 版本是比pod 'SensorsAnalyticsSDK', '4.3.2' 的时间早的。这是从这个版本之后，兼容出现问题的。

**Comment by zhangyanneng** [comment]
在SAScrollViewDelegateProxy这个类中
<img width="809" alt="image" src="https://user-images.githubusercontent.com/15318508/193023464-ff675b90-73d8-453b-95c7-54b7194bf6cf.png">
这块的逻辑是有问题的，如果tableview或collectionView使用代理做消息转发的时候会被中断，可以按下面方式修改：
![image](https://user-images.githubusercontent.com/15318508/193024803-2c33bbc8-848d-4937-94b9-593706458d0c.png)

，这样就不影响别的地方的执行

**Comment by minchaozhang** [comment]
可升级最新版本，看看是否还存在相关问题
