### ISSUE TITLE
当打点数据很多的时候，后续上报都是一次一条数据了

### ISSUE THREAD

**Issue by seaguest** [sensorsdata/sa-sdk-ios#99]
Hi,

我用最新版本的代码4.4.0做了一个压测，一次打点10W条（for循环track），理论上是每隔15s上传或者满50条才上报，但大约从2W条开始，1s内上报很多次，每次就很少的数据（1-10条内），这个和15s或者50条的条件不符合。

当数据量小的时候，一切都是正常的，但是数量大的时候就表现的不一致了。而且大约只有5w条左右的数据上报了，后续一直没有新数据上报。

**Comment by minchaozhang** [comment]
能否提供下测试的代码

**Comment by seaguest** [comment]
貌似是缓存大小导致的，设置大了之后就没有问题了。
